(setq perldoc-obarray (make-vector 1519 nil))
;; Functions
(mapc (lambda (func)
         (set (intern func perldoc-obarray) t))
'(
"*" "-A" "-B" "-C" "-M" "-O" "-R" "-S" "-T" "-W" "-X" "-b" "-c" "-d" "-e"
"-f" "-g" "-k" "-l" "-o" "-p" "-r" "-s" "-t" "-u" "-w" "-x" "-z" "__FILE__"
"__LINE__" "__PACKAGE__" "__SUB__" "abs" "accept" "alarm" "atan2" "bind"
"binmode" "bless" "break" "caller" "chdir" "chmod" "chomp" "chop" "chown"
"chr" "chroot" "close" "closedir" "connect" "continue" "cos" "crypt"
"dbmclose" "dbmopen" "defined" "delete" "die" "do" "dump" "each" "endgrent"
"endhostent" "endnetent" "endprotoent" "endpwent" "endservent" "eof" "eval"
"evalbytes" "exec" "exists" "exit" "exp" "fc" "fcntl" "fileno" "flock"
"fork" "format" "formline" "getc" "getgrent" "getgrgid" "getgrnam"
"gethostbyaddr" "gethostbyname" "gethostent" "getlogin" "getnetbyaddr"
"getnetbyname" "getnetent" "getpeername" "getpgrp" "getppid" "getpriority"
"getprotobyname" "getprotobynumber" "getprotoent" "getpwent" "getpwnam"
"getpwuid" "getservbyname" "getservbyport" "getservent" "getsockname"
"getsockopt" "glob" "gmtime" "goto" "grep" "hex" "import" "index" "int"
"ioctl" "join" "keys" "kill" "last" "lc" "lcfirst" "length" "link" "listen"
"local" "localtime" "lock" "log" "lstat" "m" "map" "mkdir" "msgctl"
"msgget" "msgrcv" "msgsnd" "my" "next" "no" "oct" "open" "opendir" "ord"
"our" "pack" "package" "pipe" "pop" "pos" "print" "printf" "prototype"
"push" "q" "qq" "qr" "quotemeta" "qw" "qx" "rand" "read" "readdir"
"readline" "readlink" "readpipe" "recv" "redo" "ref" "rename" "require"
"reset" "return" "reverse" "rewinddir" "rindex" "rmdir" "s" "say" "scalar"
"seek" "seekdir" "select" "semctl" "semget" "semop" "send" "setgrent"
"sethostent" "setnetent" "setpgrp" "setpriority" "setprotoent" "setpwent"
"setservent" "setsockopt" "shift" "shmctl" "shmget" "shmread" "shmwrite"
"shutdown" "sin" "sleep" "socket" "socketpair" "sort" "splice" "split"
"sprintf" "sqrt" "srand" "stat" "state" "study" "sub" "substr" "symlink"
"syscall" "sysopen" "sysread" "sysseek" "system" "syswrite" "tell"
"telldir" "tie" "tied" "time" "times" "tr" "truncate" "uc" "ucfirst"
"umask" "undef" "unlink" "unpack" "unshift" "untie" "use" "utime" "values"
"vec" "wait" "waitpid" "wantarray" "warn" "write" "y"))

;; Modules
(mapc (lambda (mod)
         (intern mod perldoc-obarray))
'(
"AE" "Algorithm::C3" "Algorithm::Diff" "Algorithm::Diff::XS"
"Algorithm::DiffOld" "Algorithm::Merge" "AnyDBM_File" "AnyEvent"
"AnyEvent::DNS" "AnyEvent::Debug" "AnyEvent::FAQ" "AnyEvent::Handle"
"AnyEvent::I3" "AnyEvent::IO" "AnyEvent::IO::IOAIO" "AnyEvent::IO::Perl"
"AnyEvent::Impl::Cocoa" "AnyEvent::Impl::EV" "AnyEvent::Impl::Event"
"AnyEvent::Impl::EventLib" "AnyEvent::Impl::FLTK" "AnyEvent::Impl::Glib"
"AnyEvent::Impl::IOAsync" "AnyEvent::Impl::Irssi" "AnyEvent::Impl::POE"
"AnyEvent::Impl::Perl" "AnyEvent::Impl::Qt" "AnyEvent::Impl::Tk"
"AnyEvent::Intro" "AnyEvent::Log" "AnyEvent::Loop" "AnyEvent::Socket"
"AnyEvent::Strict" "AnyEvent::TLS" "AnyEvent::Util" "App::Cpan"
"App::Prove" "App::Prove::State" "App::Prove::State::Result"
"App::Prove::State::Result::Test" "AppConfig" "AppConfig::Args"
"AppConfig::CGI" "AppConfig::File" "AppConfig::Getopt" "AppConfig::State"
"AppConfig::Sys" "AptPkg" "AptPkg::Cache" "AptPkg::Config"
"AptPkg::PkgRecords" "AptPkg::Policy" "AptPkg::Source" "AptPkg::System"
"AptPkg::Version" "AptPkg::hash" "Archive::Extract" "Archive::Tar"
"Archive::Tar::Constant" "Archive::Tar::File" "Archive::Zip"
"Archive::Zip::Archive" "Archive::Zip::BufferedFileHandle"
"Archive::Zip::DirectoryMember" "Archive::Zip::FAQ"
"Archive::Zip::FileMember" "Archive::Zip::Member"
"Archive::Zip::MemberRead" "Archive::Zip::MockFileHandle"
"Archive::Zip::NewFileMember" "Archive::Zip::StringMember"
"Archive::Zip::Tree" "Archive::Zip::ZipFileMember" "Async::Interrupt"
"Attribute::Handlers" "Attribute::Params::Validate" "Authen::SASL"
"Authen::SASL::CRAM_MD5" "Authen::SASL::EXTERNAL" "Authen::SASL::Perl"
"Authen::SASL::Perl::ANONYMOUS" "Authen::SASL::Perl::CRAM_MD5"
"Authen::SASL::Perl::DIGEST_MD5" "Authen::SASL::Perl::EXTERNAL"
"Authen::SASL::Perl::GSSAPI" "Authen::SASL::Perl::LOGIN"
"Authen::SASL::Perl::PLAIN" "AutoLoader" "AutoSplit" "B" "B::Concise"
"B::Debug" "B::Deparse" "B::Keywords" "B::Lint" "B::Lint::Debug"
"B::Showlex" "B::Terse" "B::Xref" "Benchmark" "Bit::Vector"
"Bit::Vector::Overload" "Bit::Vector::String" "CGI" "CGI::Apache"
"CGI::Carp" "CGI::Cookie" "CGI::Pretty" "CGI::Push" "CGI::Switch"
"CGI::Util" "CIL" "CIL::Attachment" "CIL::Base" "CIL::Command"
"CIL::Command::Add" "CIL::Command::Am" "CIL::Command::Attach"
"CIL::Command::Comment" "CIL::Command::DependsOn" "CIL::Command::Edit"
"CIL::Command::Extract" "CIL::Command::Fsck" "CIL::Command::Init"
"CIL::Command::Label" "CIL::Command::List" "CIL::Command::Precedes"
"CIL::Command::Show" "CIL::Command::Status" "CIL::Command::Steal"
"CIL::Command::Summary" "CIL::Command::Track" "CIL::Command::Work"
"CIL::Comment" "CIL::Git" "CIL::Issue" "CIL::Utils" "CORE" "CPAN"
"CPAN::API::HOWTO" "CPAN::Author" "CPAN::Bundle" "CPAN::CacheMgr"
"CPAN::Complete" "CPAN::Debug" "CPAN::DeferredCode" "CPAN::Distribution"
"CPAN::Distroprefs" "CPAN::Distrostatus"
"CPAN::Exception::RecursiveDependency" "CPAN::Exception::blocked_urllist"
"CPAN::Exception::yaml_not_installed" "CPAN::Exception::yaml_process_error"
"CPAN::FTP" "CPAN::FTP::netrc" "CPAN::FirstTime" "CPAN::HTTP::Client"
"CPAN::HTTP::Credentials" "CPAN::HandleConfig" "CPAN::Index"
"CPAN::InfoObj" "CPAN::Kwalify" "CPAN::LWP::UserAgent" "CPAN::Meta"
"CPAN::Meta::Converter" "CPAN::Meta::Feature" "CPAN::Meta::History"
"CPAN::Meta::Prereqs" "CPAN::Meta::Requirements" "CPAN::Meta::Spec"
"CPAN::Meta::Validator" "CPAN::Meta::YAML" "CPAN::Mirrors" "CPAN::Module"
"CPAN::Nox" "CPAN::Prompt" "CPAN::Queue" "CPAN::Shell" "CPAN::Tarzip"
"CPAN::URL" "CPAN::Version" "CPANPLUS" "CPANPLUS::Backend"
"CPANPLUS::Backend::RV" "CPANPLUS::Config" "CPANPLUS::Config::HomeEnv"
"CPANPLUS::Config::System" "CPANPLUS::Configure"
"CPANPLUS::Configure::Setup" "CPANPLUS::Dist" "CPANPLUS::Dist::Autobundle"
"CPANPLUS::Dist::Base" "CPANPLUS::Dist::Build"
"CPANPLUS::Dist::Build::Constants" "CPANPLUS::Dist::MM"
"CPANPLUS::Dist::Sample" "CPANPLUS::Error" "CPANPLUS::FAQ"
"CPANPLUS::Hacking" "CPANPLUS::Internals" "CPANPLUS::Internals::Constants"
"CPANPLUS::Internals::Constants::Report" "CPANPLUS::Internals::Extract"
"CPANPLUS::Internals::Fetch" "CPANPLUS::Internals::Report"
"CPANPLUS::Internals::Search" "CPANPLUS::Internals::Source"
"CPANPLUS::Internals::Source::Memory" "CPANPLUS::Internals::Source::SQLite"
"CPANPLUS::Internals::Source::SQLite::Tie" "CPANPLUS::Internals::Utils"
"CPANPLUS::Internals::Utils::Autoflush" "CPANPLUS::Module"
"CPANPLUS::Module::Author" "CPANPLUS::Module::Author::Fake"
"CPANPLUS::Module::Checksums" "CPANPLUS::Module::Fake"
"CPANPLUS::Module::Signature" "CPANPLUS::Selfupdate" "CPANPLUS::Shell"
"CPANPLUS::Shell::Classic" "CPANPLUS::Shell::Default"
"CPANPLUS::Shell::Default::Plugins::CustomSource"
"CPANPLUS::Shell::Default::Plugins::HOWTO"
"CPANPLUS::Shell::Default::Plugins::Remote"
"CPANPLUS::Shell::Default::Plugins::Source" "Cairo" "Cairo::Install::Files"
"Capture::Tiny" "Carp" "Carp::Clan" "Carp::Heavy" "Class::Accessor"
"Class::Accessor::Fast" "Class::Accessor::Faster" "Class::C3"
"Class::C3::XS" "Class::C3::next" "Class::Load" "Class::Load::PP"
"Class::Singleton" "Class::Struct" "Clone" "Compress::Raw::Bzip2"
"Compress::Raw::Zlib" "Compress::Zlib" "Config" "Config::Extensions"
"Config::Perl::V" "Convert::BinHex" "Crypt::PasswdMD5" "Cwd" "DB"
"DBM_Filter" "DBM_Filter::compress" "DBM_Filter::encode"
"DBM_Filter::int32" "DBM_Filter::null" "DBM_Filter::utf8" "DB_File"
"Data::Dumper" "Data::OptList" "Date::Calc" "Date::Calc::Object"
"Date::Calc::PP" "Date::Calc::XS" "Date::Calendar"
"Date::Calendar::Profiles" "Date::Calendar::Year" "Date::Format"
"Date::Language" "Date::Language::Afar" "Date::Language::Amharic"
"Date::Language::Austrian" "Date::Language::Brazilian"
"Date::Language::Bulgarian" "Date::Language::Chinese"
"Date::Language::Chinese_GB" "Date::Language::Czech"
"Date::Language::Danish" "Date::Language::Dutch" "Date::Language::English"
"Date::Language::Finnish" "Date::Language::French" "Date::Language::Gedeo"
"Date::Language::German" "Date::Language::Greek"
"Date::Language::Hungarian" "Date::Language::Icelandic"
"Date::Language::Italian" "Date::Language::Norwegian"
"Date::Language::Oromo" "Date::Language::Romanian"
"Date::Language::Russian" "Date::Language::Russian_cp1251"
"Date::Language::Russian_koi8r" "Date::Language::Sidama"
"Date::Language::Somali" "Date::Language::Spanish"
"Date::Language::Swedish" "Date::Language::Tigrinya"
"Date::Language::TigrinyaEritrean" "Date::Language::TigrinyaEthiopian"
"Date::Language::Turkish" "Date::Parse" "DateTime" "DateTime::Duration"
"DateTime::Helpers" "DateTime::Infinite" "DateTime::LeapSecond"
"DateTime::Locale" "DateTime::Locale::Base" "DateTime::Locale::Catalog"
"DateTime::Locale::aa" "DateTime::Locale::aa_DJ" "DateTime::Locale::aa_ER"
"DateTime::Locale::aa_ER_SAAHO" "DateTime::Locale::aa_ET"
"DateTime::Locale::af" "DateTime::Locale::af_NA" "DateTime::Locale::af_ZA"
"DateTime::Locale::ak" "DateTime::Locale::ak_GH" "DateTime::Locale::am"
"DateTime::Locale::am_ET" "DateTime::Locale::ar" "DateTime::Locale::ar_AE"
"DateTime::Locale::ar_BH" "DateTime::Locale::ar_DZ"
"DateTime::Locale::ar_EG" "DateTime::Locale::ar_IQ"
"DateTime::Locale::ar_JO" "DateTime::Locale::ar_KW"
"DateTime::Locale::ar_LB" "DateTime::Locale::ar_LY"
"DateTime::Locale::ar_MA" "DateTime::Locale::ar_OM"
"DateTime::Locale::ar_QA" "DateTime::Locale::ar_SA"
"DateTime::Locale::ar_SD" "DateTime::Locale::ar_SY"
"DateTime::Locale::ar_TN" "DateTime::Locale::ar_YE" "DateTime::Locale::as"
"DateTime::Locale::as_IN" "DateTime::Locale::az" "DateTime::Locale::az_AZ"
"DateTime::Locale::az_Cyrl" "DateTime::Locale::az_Cyrl_AZ"
"DateTime::Locale::az_Latn" "DateTime::Locale::az_Latn_AZ"
"DateTime::Locale::be" "DateTime::Locale::be_BY" "DateTime::Locale::bg"
"DateTime::Locale::bg_BG" "DateTime::Locale::bn" "DateTime::Locale::bn_BD"
"DateTime::Locale::bn_IN" "DateTime::Locale::bo" "DateTime::Locale::bo_CN"
"DateTime::Locale::bo_IN" "DateTime::Locale::bs" "DateTime::Locale::bs_BA"
"DateTime::Locale::byn" "DateTime::Locale::byn_ER" "DateTime::Locale::ca"
"DateTime::Locale::ca_ES" "DateTime::Locale::cch"
"DateTime::Locale::cch_NG" "DateTime::Locale::cop" "DateTime::Locale::cs"
"DateTime::Locale::cs_CZ" "DateTime::Locale::cy" "DateTime::Locale::cy_GB"
"DateTime::Locale::da" "DateTime::Locale::da_DK" "DateTime::Locale::de"
"DateTime::Locale::de_AT" "DateTime::Locale::de_BE"
"DateTime::Locale::de_CH" "DateTime::Locale::de_DE"
"DateTime::Locale::de_LI" "DateTime::Locale::de_LU" "DateTime::Locale::dv"
"DateTime::Locale::dv_MV" "DateTime::Locale::dz" "DateTime::Locale::dz_BT"
"DateTime::Locale::ee" "DateTime::Locale::ee_GH" "DateTime::Locale::ee_TG"
"DateTime::Locale::el" "DateTime::Locale::el_CY" "DateTime::Locale::el_GR"
"DateTime::Locale::el_POLYTON" "DateTime::Locale::en"
"DateTime::Locale::en_AS" "DateTime::Locale::en_AU"
"DateTime::Locale::en_BE" "DateTime::Locale::en_BW"
"DateTime::Locale::en_BZ" "DateTime::Locale::en_CA"
"DateTime::Locale::en_Dsrt" "DateTime::Locale::en_Dsrt_US"
"DateTime::Locale::en_GB" "DateTime::Locale::en_GU"
"DateTime::Locale::en_HK" "DateTime::Locale::en_IE"
"DateTime::Locale::en_IN" "DateTime::Locale::en_JM"
"DateTime::Locale::en_MH" "DateTime::Locale::en_MP"
"DateTime::Locale::en_MT" "DateTime::Locale::en_NA"
"DateTime::Locale::en_NZ" "DateTime::Locale::en_PH"
"DateTime::Locale::en_PK" "DateTime::Locale::en_SG"
"DateTime::Locale::en_Shaw" "DateTime::Locale::en_TT"
"DateTime::Locale::en_UM" "DateTime::Locale::en_US"
"DateTime::Locale::en_US_POSIX" "DateTime::Locale::en_VI"
"DateTime::Locale::en_ZA" "DateTime::Locale::en_ZW" "DateTime::Locale::eo"
"DateTime::Locale::es" "DateTime::Locale::es_AR" "DateTime::Locale::es_BO"
"DateTime::Locale::es_CL" "DateTime::Locale::es_CO"
"DateTime::Locale::es_CR" "DateTime::Locale::es_DO"
"DateTime::Locale::es_EC" "DateTime::Locale::es_ES"
"DateTime::Locale::es_GT" "DateTime::Locale::es_HN"
"DateTime::Locale::es_MX" "DateTime::Locale::es_NI"
"DateTime::Locale::es_PA" "DateTime::Locale::es_PE"
"DateTime::Locale::es_PR" "DateTime::Locale::es_PY"
"DateTime::Locale::es_SV" "DateTime::Locale::es_US"
"DateTime::Locale::es_UY" "DateTime::Locale::es_VE" "DateTime::Locale::et"
"DateTime::Locale::et_EE" "DateTime::Locale::eu" "DateTime::Locale::eu_ES"
"DateTime::Locale::fa" "DateTime::Locale::fa_AF" "DateTime::Locale::fa_IR"
"DateTime::Locale::fi" "DateTime::Locale::fi_FI" "DateTime::Locale::fil"
"DateTime::Locale::fil_PH" "DateTime::Locale::fo" "DateTime::Locale::fo_FO"
"DateTime::Locale::fr" "DateTime::Locale::fr_BE" "DateTime::Locale::fr_CA"
"DateTime::Locale::fr_CH" "DateTime::Locale::fr_FR"
"DateTime::Locale::fr_LU" "DateTime::Locale::fr_MC"
"DateTime::Locale::fr_SN" "DateTime::Locale::fur"
"DateTime::Locale::fur_IT" "DateTime::Locale::ga" "DateTime::Locale::ga_IE"
"DateTime::Locale::gaa" "DateTime::Locale::gaa_GH" "DateTime::Locale::gez"
"DateTime::Locale::gez_ER" "DateTime::Locale::gez_ET"
"DateTime::Locale::gl" "DateTime::Locale::gl_ES" "DateTime::Locale::gsw"
"DateTime::Locale::gsw_CH" "DateTime::Locale::gu" "DateTime::Locale::gu_IN"
"DateTime::Locale::gv" "DateTime::Locale::gv_GB" "DateTime::Locale::ha"
"DateTime::Locale::ha_Arab" "DateTime::Locale::ha_Arab_NG"
"DateTime::Locale::ha_Arab_SD" "DateTime::Locale::ha_GH"
"DateTime::Locale::ha_Latn" "DateTime::Locale::ha_Latn_GH"
"DateTime::Locale::ha_Latn_NE" "DateTime::Locale::ha_Latn_NG"
"DateTime::Locale::ha_NE" "DateTime::Locale::ha_NG"
"DateTime::Locale::ha_SD" "DateTime::Locale::haw"
"DateTime::Locale::haw_US" "DateTime::Locale::he" "DateTime::Locale::he_IL"
"DateTime::Locale::hi" "DateTime::Locale::hi_IN" "DateTime::Locale::hr"
"DateTime::Locale::hr_HR" "DateTime::Locale::hu" "DateTime::Locale::hu_HU"
"DateTime::Locale::hy" "DateTime::Locale::hy_AM"
"DateTime::Locale::hy_AM_REVISED" "DateTime::Locale::ia"
"DateTime::Locale::id" "DateTime::Locale::id_ID" "DateTime::Locale::ig"
"DateTime::Locale::ig_NG" "DateTime::Locale::ii" "DateTime::Locale::ii_CN"
"DateTime::Locale::is" "DateTime::Locale::is_IS" "DateTime::Locale::it"
"DateTime::Locale::it_CH" "DateTime::Locale::it_IT" "DateTime::Locale::iu"
"DateTime::Locale::ja" "DateTime::Locale::ja_JP" "DateTime::Locale::ka"
"DateTime::Locale::ka_GE" "DateTime::Locale::kaj"
"DateTime::Locale::kaj_NG" "DateTime::Locale::kam"
"DateTime::Locale::kam_KE" "DateTime::Locale::kcg"
"DateTime::Locale::kcg_NG" "DateTime::Locale::kfo"
"DateTime::Locale::kfo_CI" "DateTime::Locale::kk"
"DateTime::Locale::kk_Cyrl" "DateTime::Locale::kk_Cyrl_KZ"
"DateTime::Locale::kk_KZ" "DateTime::Locale::kl" "DateTime::Locale::kl_GL"
"DateTime::Locale::km" "DateTime::Locale::km_KH" "DateTime::Locale::kn"
"DateTime::Locale::kn_IN" "DateTime::Locale::ko" "DateTime::Locale::ko_KR"
"DateTime::Locale::kok" "DateTime::Locale::kok_IN" "DateTime::Locale::kpe"
"DateTime::Locale::kpe_GN" "DateTime::Locale::kpe_LR"
"DateTime::Locale::ku" "DateTime::Locale::ku_Arab"
"DateTime::Locale::ku_Arab_IQ" "DateTime::Locale::ku_Arab_IR"
"DateTime::Locale::ku_Arab_SY" "DateTime::Locale::ku_IQ"
"DateTime::Locale::ku_IR" "DateTime::Locale::ku_Latn"
"DateTime::Locale::ku_Latn_TR" "DateTime::Locale::ku_SY"
"DateTime::Locale::ku_TR" "DateTime::Locale::kw" "DateTime::Locale::kw_GB"
"DateTime::Locale::ky" "DateTime::Locale::ky_KG" "DateTime::Locale::ln"
"DateTime::Locale::ln_CD" "DateTime::Locale::ln_CG" "DateTime::Locale::lo"
"DateTime::Locale::lo_LA" "DateTime::Locale::lt" "DateTime::Locale::lt_LT"
"DateTime::Locale::lv" "DateTime::Locale::lv_LV" "DateTime::Locale::mk"
"DateTime::Locale::mk_MK" "DateTime::Locale::ml" "DateTime::Locale::ml_IN"
"DateTime::Locale::mn" "DateTime::Locale::mn_CN"
"DateTime::Locale::mn_Cyrl" "DateTime::Locale::mn_Cyrl_MN"
"DateTime::Locale::mn_MN" "DateTime::Locale::mn_Mong"
"DateTime::Locale::mn_Mong_CN" "DateTime::Locale::mo"
"DateTime::Locale::mr" "DateTime::Locale::mr_IN" "DateTime::Locale::ms"
"DateTime::Locale::ms_BN" "DateTime::Locale::ms_MY" "DateTime::Locale::mt"
"DateTime::Locale::mt_MT" "DateTime::Locale::my" "DateTime::Locale::my_MM"
"DateTime::Locale::nb" "DateTime::Locale::nb_NO" "DateTime::Locale::nds"
"DateTime::Locale::nds_DE" "DateTime::Locale::ne" "DateTime::Locale::ne_IN"
"DateTime::Locale::ne_NP" "DateTime::Locale::nl" "DateTime::Locale::nl_BE"
"DateTime::Locale::nl_NL" "DateTime::Locale::nn" "DateTime::Locale::nn_NO"
"DateTime::Locale::no" "DateTime::Locale::nr" "DateTime::Locale::nr_ZA"
"DateTime::Locale::nso" "DateTime::Locale::nso_ZA" "DateTime::Locale::ny"
"DateTime::Locale::ny_MW" "DateTime::Locale::oc" "DateTime::Locale::oc_FR"
"DateTime::Locale::om" "DateTime::Locale::om_ET" "DateTime::Locale::om_KE"
"DateTime::Locale::or" "DateTime::Locale::or_IN" "DateTime::Locale::pa"
"DateTime::Locale::pa_Arab" "DateTime::Locale::pa_Arab_PK"
"DateTime::Locale::pa_Guru" "DateTime::Locale::pa_Guru_IN"
"DateTime::Locale::pa_IN" "DateTime::Locale::pa_PK" "DateTime::Locale::pl"
"DateTime::Locale::pl_PL" "DateTime::Locale::ps" "DateTime::Locale::ps_AF"
"DateTime::Locale::pt" "DateTime::Locale::pt_BR" "DateTime::Locale::pt_PT"
"DateTime::Locale::ro" "DateTime::Locale::ro_MD" "DateTime::Locale::ro_RO"
"DateTime::Locale::root" "DateTime::Locale::ru" "DateTime::Locale::ru_RU"
"DateTime::Locale::ru_UA" "DateTime::Locale::rw" "DateTime::Locale::rw_RW"
"DateTime::Locale::sa" "DateTime::Locale::sa_IN" "DateTime::Locale::se"
"DateTime::Locale::se_FI" "DateTime::Locale::se_NO" "DateTime::Locale::sh"
"DateTime::Locale::sh_BA" "DateTime::Locale::sh_CS"
"DateTime::Locale::sh_YU" "DateTime::Locale::si" "DateTime::Locale::si_LK"
"DateTime::Locale::sid" "DateTime::Locale::sid_ET" "DateTime::Locale::sk"
"DateTime::Locale::sk_SK" "DateTime::Locale::sl" "DateTime::Locale::sl_SI"
"DateTime::Locale::so" "DateTime::Locale::so_DJ" "DateTime::Locale::so_ET"
"DateTime::Locale::so_KE" "DateTime::Locale::so_SO" "DateTime::Locale::sq"
"DateTime::Locale::sq_AL" "DateTime::Locale::sr" "DateTime::Locale::sr_BA"
"DateTime::Locale::sr_CS" "DateTime::Locale::sr_Cyrl"
"DateTime::Locale::sr_Cyrl_BA" "DateTime::Locale::sr_Cyrl_CS"
"DateTime::Locale::sr_Cyrl_ME" "DateTime::Locale::sr_Cyrl_RS"
"DateTime::Locale::sr_Cyrl_YU" "DateTime::Locale::sr_Latn"
"DateTime::Locale::sr_Latn_BA" "DateTime::Locale::sr_Latn_CS"
"DateTime::Locale::sr_Latn_ME" "DateTime::Locale::sr_Latn_RS"
"DateTime::Locale::sr_Latn_YU" "DateTime::Locale::sr_ME"
"DateTime::Locale::sr_RS" "DateTime::Locale::sr_YU" "DateTime::Locale::ss"
"DateTime::Locale::ss_SZ" "DateTime::Locale::ss_ZA" "DateTime::Locale::st"
"DateTime::Locale::st_LS" "DateTime::Locale::st_ZA" "DateTime::Locale::sv"
"DateTime::Locale::sv_FI" "DateTime::Locale::sv_SE" "DateTime::Locale::sw"
"DateTime::Locale::sw_KE" "DateTime::Locale::sw_TZ" "DateTime::Locale::syr"
"DateTime::Locale::syr_SY" "DateTime::Locale::ta" "DateTime::Locale::ta_IN"
"DateTime::Locale::te" "DateTime::Locale::te_IN" "DateTime::Locale::tg"
"DateTime::Locale::tg_Cyrl" "DateTime::Locale::tg_Cyrl_TJ"
"DateTime::Locale::tg_TJ" "DateTime::Locale::th" "DateTime::Locale::th_TH"
"DateTime::Locale::ti" "DateTime::Locale::ti_ER" "DateTime::Locale::ti_ET"
"DateTime::Locale::tig" "DateTime::Locale::tig_ER" "DateTime::Locale::tl"
"DateTime::Locale::tn" "DateTime::Locale::tn_ZA" "DateTime::Locale::to"
"DateTime::Locale::to_TO" "DateTime::Locale::tr" "DateTime::Locale::tr_TR"
"DateTime::Locale::trv" "DateTime::Locale::trv_TW" "DateTime::Locale::ts"
"DateTime::Locale::ts_ZA" "DateTime::Locale::tt" "DateTime::Locale::tt_RU"
"DateTime::Locale::ug" "DateTime::Locale::ug_Arab"
"DateTime::Locale::ug_Arab_CN" "DateTime::Locale::ug_CN"
"DateTime::Locale::uk" "DateTime::Locale::uk_UA" "DateTime::Locale::ur"
"DateTime::Locale::ur_IN" "DateTime::Locale::ur_PK" "DateTime::Locale::uz"
"DateTime::Locale::uz_AF" "DateTime::Locale::uz_Arab"
"DateTime::Locale::uz_Arab_AF" "DateTime::Locale::uz_Cyrl"
"DateTime::Locale::uz_Cyrl_UZ" "DateTime::Locale::uz_Latn"
"DateTime::Locale::uz_Latn_UZ" "DateTime::Locale::uz_UZ"
"DateTime::Locale::ve" "DateTime::Locale::ve_ZA" "DateTime::Locale::vi"
"DateTime::Locale::vi_VN" "DateTime::Locale::wal"
"DateTime::Locale::wal_ET" "DateTime::Locale::wo"
"DateTime::Locale::wo_Latn" "DateTime::Locale::wo_Latn_SN"
"DateTime::Locale::wo_SN" "DateTime::Locale::xh" "DateTime::Locale::xh_ZA"
"DateTime::Locale::yo" "DateTime::Locale::yo_NG" "DateTime::Locale::zh"
"DateTime::Locale::zh_CN" "DateTime::Locale::zh_HK"
"DateTime::Locale::zh_Hans" "DateTime::Locale::zh_Hans_CN"
"DateTime::Locale::zh_Hans_HK" "DateTime::Locale::zh_Hans_MO"
"DateTime::Locale::zh_Hans_SG" "DateTime::Locale::zh_Hant"
"DateTime::Locale::zh_Hant_HK" "DateTime::Locale::zh_Hant_MO"
"DateTime::Locale::zh_Hant_TW" "DateTime::Locale::zh_MO"
"DateTime::Locale::zh_SG" "DateTime::Locale::zh_TW" "DateTime::Locale::zu"
"DateTime::Locale::zu_ZA" "DateTime::LocaleCatalog" "DateTime::TimeZone"
"DateTime::TimeZone::Africa::Abidjan" "DateTime::TimeZone::Africa::Accra"
"DateTime::TimeZone::Africa::Addis_Ababa"
"DateTime::TimeZone::Africa::Algiers" "DateTime::TimeZone::Africa::Asmara"
"DateTime::TimeZone::Africa::Bamako" "DateTime::TimeZone::Africa::Bangui"
"DateTime::TimeZone::Africa::Banjul" "DateTime::TimeZone::Africa::Bissau"
"DateTime::TimeZone::Africa::Blantyre"
"DateTime::TimeZone::Africa::Brazzaville"
"DateTime::TimeZone::Africa::Bujumbura" "DateTime::TimeZone::Africa::Cairo"
"DateTime::TimeZone::Africa::Casablanca"
"DateTime::TimeZone::Africa::Ceuta" "DateTime::TimeZone::Africa::Conakry"
"DateTime::TimeZone::Africa::Dakar"
"DateTime::TimeZone::Africa::Dar_es_Salaam"
"DateTime::TimeZone::Africa::Djibouti" "DateTime::TimeZone::Africa::Douala"
"DateTime::TimeZone::Africa::El_Aaiun"
"DateTime::TimeZone::Africa::Freetown"
"DateTime::TimeZone::Africa::Gaborone" "DateTime::TimeZone::Africa::Harare"
"DateTime::TimeZone::Africa::Johannesburg"
"DateTime::TimeZone::Africa::Kampala"
"DateTime::TimeZone::Africa::Khartoum" "DateTime::TimeZone::Africa::Kigali"
"DateTime::TimeZone::Africa::Kinshasa" "DateTime::TimeZone::Africa::Lagos"
"DateTime::TimeZone::Africa::Libreville" "DateTime::TimeZone::Africa::Lome"
"DateTime::TimeZone::Africa::Luanda"
"DateTime::TimeZone::Africa::Lubumbashi"
"DateTime::TimeZone::Africa::Lusaka" "DateTime::TimeZone::Africa::Malabo"
"DateTime::TimeZone::Africa::Maputo" "DateTime::TimeZone::Africa::Maseru"
"DateTime::TimeZone::Africa::Mbabane"
"DateTime::TimeZone::Africa::Mogadishu"
"DateTime::TimeZone::Africa::Monrovia"
"DateTime::TimeZone::Africa::Nairobi"
"DateTime::TimeZone::Africa::Ndjamena" "DateTime::TimeZone::Africa::Niamey"
"DateTime::TimeZone::Africa::Nouakchott"
"DateTime::TimeZone::Africa::Ouagadougou"
"DateTime::TimeZone::Africa::Porto_Novo"
"DateTime::TimeZone::Africa::Sao_Tome"
"DateTime::TimeZone::Africa::Tripoli" "DateTime::TimeZone::Africa::Tunis"
"DateTime::TimeZone::Africa::Windhoek" "DateTime::TimeZone::America::Adak"
"DateTime::TimeZone::America::Anchorage"
"DateTime::TimeZone::America::Antigua"
"DateTime::TimeZone::America::Araguaina"
"DateTime::TimeZone::America::Argentina::Buenos_Aires"
"DateTime::TimeZone::America::Argentina::Catamarca"
"DateTime::TimeZone::America::Argentina::Cordoba"
"DateTime::TimeZone::America::Argentina::Jujuy"
"DateTime::TimeZone::America::Argentina::La_Rioja"
"DateTime::TimeZone::America::Argentina::Mendoza"
"DateTime::TimeZone::America::Argentina::Rio_Gallegos"
"DateTime::TimeZone::America::Argentina::Salta"
"DateTime::TimeZone::America::Argentina::San_Juan"
"DateTime::TimeZone::America::Argentina::San_Luis"
"DateTime::TimeZone::America::Argentina::Tucuman"
"DateTime::TimeZone::America::Argentina::Ushuaia"
"DateTime::TimeZone::America::Asuncion"
"DateTime::TimeZone::America::Atikokan"
"DateTime::TimeZone::America::Bahia"
"DateTime::TimeZone::America::Bahia_Banderas"
"DateTime::TimeZone::America::Barbados"
"DateTime::TimeZone::America::Belem" "DateTime::TimeZone::America::Belize"
"DateTime::TimeZone::America::Blanc_Sablon"
"DateTime::TimeZone::America::Boa_Vista"
"DateTime::TimeZone::America::Bogota" "DateTime::TimeZone::America::Boise"
"DateTime::TimeZone::America::Cambridge_Bay"
"DateTime::TimeZone::America::Campo_Grande"
"DateTime::TimeZone::America::Cancun"
"DateTime::TimeZone::America::Caracas"
"DateTime::TimeZone::America::Cayenne"
"DateTime::TimeZone::America::Cayman"
"DateTime::TimeZone::America::Chicago"
"DateTime::TimeZone::America::Chihuahua"
"DateTime::TimeZone::America::Costa_Rica"
"DateTime::TimeZone::America::Creston"
"DateTime::TimeZone::America::Cuiaba"
"DateTime::TimeZone::America::Curacao"
"DateTime::TimeZone::America::Danmarkshavn"
"DateTime::TimeZone::America::Dawson"
"DateTime::TimeZone::America::Dawson_Creek"
"DateTime::TimeZone::America::Denver"
"DateTime::TimeZone::America::Detroit"
"DateTime::TimeZone::America::Edmonton"
"DateTime::TimeZone::America::Eirunepe"
"DateTime::TimeZone::America::El_Salvador"
"DateTime::TimeZone::America::Fortaleza"
"DateTime::TimeZone::America::Glace_Bay"
"DateTime::TimeZone::America::Godthab"
"DateTime::TimeZone::America::Goose_Bay"
"DateTime::TimeZone::America::Grand_Turk"
"DateTime::TimeZone::America::Guatemala"
"DateTime::TimeZone::America::Guayaquil"
"DateTime::TimeZone::America::Guyana"
"DateTime::TimeZone::America::Halifax"
"DateTime::TimeZone::America::Havana"
"DateTime::TimeZone::America::Hermosillo"
"DateTime::TimeZone::America::Indiana::Indianapolis"
"DateTime::TimeZone::America::Indiana::Knox"
"DateTime::TimeZone::America::Indiana::Marengo"
"DateTime::TimeZone::America::Indiana::Petersburg"
"DateTime::TimeZone::America::Indiana::Tell_City"
"DateTime::TimeZone::America::Indiana::Vevay"
"DateTime::TimeZone::America::Indiana::Vincennes"
"DateTime::TimeZone::America::Indiana::Winamac"
"DateTime::TimeZone::America::Inuvik"
"DateTime::TimeZone::America::Iqaluit"
"DateTime::TimeZone::America::Jamaica"
"DateTime::TimeZone::America::Juneau"
"DateTime::TimeZone::America::Kentucky::Louisville"
"DateTime::TimeZone::America::Kentucky::Monticello"
"DateTime::TimeZone::America::La_Paz" "DateTime::TimeZone::America::Lima"
"DateTime::TimeZone::America::Los_Angeles"
"DateTime::TimeZone::America::Maceio"
"DateTime::TimeZone::America::Managua"
"DateTime::TimeZone::America::Manaus"
"DateTime::TimeZone::America::Martinique"
"DateTime::TimeZone::America::Matamoros"
"DateTime::TimeZone::America::Mazatlan"
"DateTime::TimeZone::America::Menominee"
"DateTime::TimeZone::America::Merida"
"DateTime::TimeZone::America::Metlakatla"
"DateTime::TimeZone::America::Mexico_City"
"DateTime::TimeZone::America::Miquelon"
"DateTime::TimeZone::America::Moncton"
"DateTime::TimeZone::America::Monterrey"
"DateTime::TimeZone::America::Montevideo"
"DateTime::TimeZone::America::Montreal"
"DateTime::TimeZone::America::Nassau"
"DateTime::TimeZone::America::New_York"
"DateTime::TimeZone::America::Nipigon" "DateTime::TimeZone::America::Nome"
"DateTime::TimeZone::America::Noronha"
"DateTime::TimeZone::America::North_Dakota::Beulah"
"DateTime::TimeZone::America::North_Dakota::Center"
"DateTime::TimeZone::America::North_Dakota::New_Salem"
"DateTime::TimeZone::America::Ojinaga"
"DateTime::TimeZone::America::Panama"
"DateTime::TimeZone::America::Pangnirtung"
"DateTime::TimeZone::America::Paramaribo"
"DateTime::TimeZone::America::Phoenix"
"DateTime::TimeZone::America::Port_au_Prince"
"DateTime::TimeZone::America::Port_of_Spain"
"DateTime::TimeZone::America::Porto_Velho"
"DateTime::TimeZone::America::Puerto_Rico"
"DateTime::TimeZone::America::Rainy_River"
"DateTime::TimeZone::America::Rankin_Inlet"
"DateTime::TimeZone::America::Recife" "DateTime::TimeZone::America::Regina"
"DateTime::TimeZone::America::Resolute"
"DateTime::TimeZone::America::Rio_Branco"
"DateTime::TimeZone::America::Santa_Isabel"
"DateTime::TimeZone::America::Santarem"
"DateTime::TimeZone::America::Santiago"
"DateTime::TimeZone::America::Santo_Domingo"
"DateTime::TimeZone::America::Sao_Paulo"
"DateTime::TimeZone::America::Scoresbysund"
"DateTime::TimeZone::America::Sitka"
"DateTime::TimeZone::America::St_Johns"
"DateTime::TimeZone::America::Swift_Current"
"DateTime::TimeZone::America::Tegucigalpa"
"DateTime::TimeZone::America::Thule"
"DateTime::TimeZone::America::Thunder_Bay"
"DateTime::TimeZone::America::Tijuana"
"DateTime::TimeZone::America::Toronto"
"DateTime::TimeZone::America::Vancouver"
"DateTime::TimeZone::America::Whitehorse"
"DateTime::TimeZone::America::Winnipeg"
"DateTime::TimeZone::America::Yakutat"
"DateTime::TimeZone::America::Yellowknife"
"DateTime::TimeZone::Antarctica::Casey"
"DateTime::TimeZone::Antarctica::Davis"
"DateTime::TimeZone::Antarctica::DumontDUrville"
"DateTime::TimeZone::Antarctica::Macquarie"
"DateTime::TimeZone::Antarctica::Mawson"
"DateTime::TimeZone::Antarctica::Palmer"
"DateTime::TimeZone::Antarctica::Rothera"
"DateTime::TimeZone::Antarctica::Syowa"
"DateTime::TimeZone::Antarctica::Vostok" "DateTime::TimeZone::Asia::Aden"
"DateTime::TimeZone::Asia::Almaty" "DateTime::TimeZone::Asia::Amman"
"DateTime::TimeZone::Asia::Anadyr" "DateTime::TimeZone::Asia::Aqtau"
"DateTime::TimeZone::Asia::Aqtobe" "DateTime::TimeZone::Asia::Ashgabat"
"DateTime::TimeZone::Asia::Baghdad" "DateTime::TimeZone::Asia::Bahrain"
"DateTime::TimeZone::Asia::Baku" "DateTime::TimeZone::Asia::Bangkok"
"DateTime::TimeZone::Asia::Beirut" "DateTime::TimeZone::Asia::Bishkek"
"DateTime::TimeZone::Asia::Brunei" "DateTime::TimeZone::Asia::Choibalsan"
"DateTime::TimeZone::Asia::Chongqing" "DateTime::TimeZone::Asia::Colombo"
"DateTime::TimeZone::Asia::Damascus" "DateTime::TimeZone::Asia::Dhaka"
"DateTime::TimeZone::Asia::Dili" "DateTime::TimeZone::Asia::Dubai"
"DateTime::TimeZone::Asia::Dushanbe" "DateTime::TimeZone::Asia::Gaza"
"DateTime::TimeZone::Asia::Harbin" "DateTime::TimeZone::Asia::Hebron"
"DateTime::TimeZone::Asia::Ho_Chi_Minh"
"DateTime::TimeZone::Asia::Hong_Kong" "DateTime::TimeZone::Asia::Hovd"
"DateTime::TimeZone::Asia::Irkutsk" "DateTime::TimeZone::Asia::Jakarta"
"DateTime::TimeZone::Asia::Jayapura" "DateTime::TimeZone::Asia::Jerusalem"
"DateTime::TimeZone::Asia::Kabul" "DateTime::TimeZone::Asia::Kamchatka"
"DateTime::TimeZone::Asia::Karachi" "DateTime::TimeZone::Asia::Kashgar"
"DateTime::TimeZone::Asia::Kathmandu" "DateTime::TimeZone::Asia::Khandyga"
"DateTime::TimeZone::Asia::Kolkata" "DateTime::TimeZone::Asia::Krasnoyarsk"
"DateTime::TimeZone::Asia::Kuala_Lumpur"
"DateTime::TimeZone::Asia::Kuching" "DateTime::TimeZone::Asia::Kuwait"
"DateTime::TimeZone::Asia::Macau" "DateTime::TimeZone::Asia::Magadan"
"DateTime::TimeZone::Asia::Makassar" "DateTime::TimeZone::Asia::Manila"
"DateTime::TimeZone::Asia::Muscat" "DateTime::TimeZone::Asia::Nicosia"
"DateTime::TimeZone::Asia::Novokuznetsk"
"DateTime::TimeZone::Asia::Novosibirsk" "DateTime::TimeZone::Asia::Omsk"
"DateTime::TimeZone::Asia::Oral" "DateTime::TimeZone::Asia::Phnom_Penh"
"DateTime::TimeZone::Asia::Pontianak" "DateTime::TimeZone::Asia::Pyongyang"
"DateTime::TimeZone::Asia::Qatar" "DateTime::TimeZone::Asia::Qyzylorda"
"DateTime::TimeZone::Asia::Rangoon" "DateTime::TimeZone::Asia::Riyadh"
"DateTime::TimeZone::Asia::Sakhalin" "DateTime::TimeZone::Asia::Samarkand"
"DateTime::TimeZone::Asia::Seoul" "DateTime::TimeZone::Asia::Shanghai"
"DateTime::TimeZone::Asia::Singapore" "DateTime::TimeZone::Asia::Taipei"
"DateTime::TimeZone::Asia::Tashkent" "DateTime::TimeZone::Asia::Tbilisi"
"DateTime::TimeZone::Asia::Tehran" "DateTime::TimeZone::Asia::Thimphu"
"DateTime::TimeZone::Asia::Tokyo" "DateTime::TimeZone::Asia::Ulaanbaatar"
"DateTime::TimeZone::Asia::Urumqi" "DateTime::TimeZone::Asia::Ust_Nera"
"DateTime::TimeZone::Asia::Vientiane"
"DateTime::TimeZone::Asia::Vladivostok" "DateTime::TimeZone::Asia::Yakutsk"
"DateTime::TimeZone::Asia::Yekaterinburg"
"DateTime::TimeZone::Asia::Yerevan" "DateTime::TimeZone::Atlantic::Azores"
"DateTime::TimeZone::Atlantic::Bermuda"
"DateTime::TimeZone::Atlantic::Canary"
"DateTime::TimeZone::Atlantic::Cape_Verde"
"DateTime::TimeZone::Atlantic::Faroe"
"DateTime::TimeZone::Atlantic::Madeira"
"DateTime::TimeZone::Atlantic::Reykjavik"
"DateTime::TimeZone::Atlantic::South_Georgia"
"DateTime::TimeZone::Atlantic::St_Helena"
"DateTime::TimeZone::Atlantic::Stanley"
"DateTime::TimeZone::Australia::Adelaide"
"DateTime::TimeZone::Australia::Brisbane"
"DateTime::TimeZone::Australia::Broken_Hill"
"DateTime::TimeZone::Australia::Currie"
"DateTime::TimeZone::Australia::Darwin"
"DateTime::TimeZone::Australia::Eucla"
"DateTime::TimeZone::Australia::Hobart"
"DateTime::TimeZone::Australia::Lindeman"
"DateTime::TimeZone::Australia::Lord_Howe"
"DateTime::TimeZone::Australia::Melbourne"
"DateTime::TimeZone::Australia::Perth"
"DateTime::TimeZone::Australia::Sydney" "DateTime::TimeZone::CET"
"DateTime::TimeZone::CST6CDT" "DateTime::TimeZone::Catalog"
"DateTime::TimeZone::EET" "DateTime::TimeZone::EST"
"DateTime::TimeZone::EST5EDT" "DateTime::TimeZone::Europe::Amsterdam"
"DateTime::TimeZone::Europe::Andorra" "DateTime::TimeZone::Europe::Athens"
"DateTime::TimeZone::Europe::Belgrade" "DateTime::TimeZone::Europe::Berlin"
"DateTime::TimeZone::Europe::Brussels"
"DateTime::TimeZone::Europe::Bucharest"
"DateTime::TimeZone::Europe::Budapest"
"DateTime::TimeZone::Europe::Chisinau"
"DateTime::TimeZone::Europe::Copenhagen"
"DateTime::TimeZone::Europe::Dublin"
"DateTime::TimeZone::Europe::Gibraltar"
"DateTime::TimeZone::Europe::Helsinki"
"DateTime::TimeZone::Europe::Istanbul"
"DateTime::TimeZone::Europe::Kaliningrad"
"DateTime::TimeZone::Europe::Kiev" "DateTime::TimeZone::Europe::Lisbon"
"DateTime::TimeZone::Europe::London"
"DateTime::TimeZone::Europe::Luxembourg"
"DateTime::TimeZone::Europe::Madrid" "DateTime::TimeZone::Europe::Malta"
"DateTime::TimeZone::Europe::Minsk" "DateTime::TimeZone::Europe::Monaco"
"DateTime::TimeZone::Europe::Moscow" "DateTime::TimeZone::Europe::Oslo"
"DateTime::TimeZone::Europe::Paris" "DateTime::TimeZone::Europe::Prague"
"DateTime::TimeZone::Europe::Riga" "DateTime::TimeZone::Europe::Rome"
"DateTime::TimeZone::Europe::Samara"
"DateTime::TimeZone::Europe::Simferopol"
"DateTime::TimeZone::Europe::Sofia" "DateTime::TimeZone::Europe::Stockholm"
"DateTime::TimeZone::Europe::Tallinn" "DateTime::TimeZone::Europe::Tirane"
"DateTime::TimeZone::Europe::Uzhgorod" "DateTime::TimeZone::Europe::Vienna"
"DateTime::TimeZone::Europe::Vilnius"
"DateTime::TimeZone::Europe::Volgograd"
"DateTime::TimeZone::Europe::Warsaw"
"DateTime::TimeZone::Europe::Zaporozhye"
"DateTime::TimeZone::Europe::Zurich" "DateTime::TimeZone::Floating"
"DateTime::TimeZone::HST" "DateTime::TimeZone::Indian::Antananarivo"
"DateTime::TimeZone::Indian::Chagos"
"DateTime::TimeZone::Indian::Christmas" "DateTime::TimeZone::Indian::Cocos"
"DateTime::TimeZone::Indian::Comoro"
"DateTime::TimeZone::Indian::Kerguelen" "DateTime::TimeZone::Indian::Mahe"
"DateTime::TimeZone::Indian::Maldives"
"DateTime::TimeZone::Indian::Mauritius"
"DateTime::TimeZone::Indian::Mayotte" "DateTime::TimeZone::Indian::Reunion"
"DateTime::TimeZone::Local" "DateTime::TimeZone::Local::Unix"
"DateTime::TimeZone::Local::VMS" "DateTime::TimeZone::MET"
"DateTime::TimeZone::MST" "DateTime::TimeZone::MST7MDT"
"DateTime::TimeZone::OffsetOnly" "DateTime::TimeZone::OlsonDB"
"DateTime::TimeZone::OlsonDB::Change"
"DateTime::TimeZone::OlsonDB::Observance"
"DateTime::TimeZone::OlsonDB::Rule" "DateTime::TimeZone::OlsonDB::Zone"
"DateTime::TimeZone::PST8PDT" "DateTime::TimeZone::Pacific::Apia"
"DateTime::TimeZone::Pacific::Auckland"
"DateTime::TimeZone::Pacific::Chatham" "DateTime::TimeZone::Pacific::Chuuk"
"DateTime::TimeZone::Pacific::Easter" "DateTime::TimeZone::Pacific::Efate"
"DateTime::TimeZone::Pacific::Enderbury"
"DateTime::TimeZone::Pacific::Fakaofo" "DateTime::TimeZone::Pacific::Fiji"
"DateTime::TimeZone::Pacific::Funafuti"
"DateTime::TimeZone::Pacific::Galapagos"
"DateTime::TimeZone::Pacific::Gambier"
"DateTime::TimeZone::Pacific::Guadalcanal"
"DateTime::TimeZone::Pacific::Guam" "DateTime::TimeZone::Pacific::Honolulu"
"DateTime::TimeZone::Pacific::Kiritimati"
"DateTime::TimeZone::Pacific::Kosrae"
"DateTime::TimeZone::Pacific::Kwajalein"
"DateTime::TimeZone::Pacific::Majuro"
"DateTime::TimeZone::Pacific::Marquesas"
"DateTime::TimeZone::Pacific::Midway" "DateTime::TimeZone::Pacific::Nauru"
"DateTime::TimeZone::Pacific::Niue" "DateTime::TimeZone::Pacific::Norfolk"
"DateTime::TimeZone::Pacific::Noumea"
"DateTime::TimeZone::Pacific::Pago_Pago"
"DateTime::TimeZone::Pacific::Palau"
"DateTime::TimeZone::Pacific::Pitcairn"
"DateTime::TimeZone::Pacific::Pohnpei"
"DateTime::TimeZone::Pacific::Port_Moresby"
"DateTime::TimeZone::Pacific::Rarotonga"
"DateTime::TimeZone::Pacific::Saipan" "DateTime::TimeZone::Pacific::Tahiti"
"DateTime::TimeZone::Pacific::Tarawa"
"DateTime::TimeZone::Pacific::Tongatapu"
"DateTime::TimeZone::Pacific::Wake" "DateTime::TimeZone::Pacific::Wallis"
"DateTime::TimeZone::UTC" "DateTime::TimeZone::WET" "DateTimePP"
"DateTimePPExtra" "Debconf::AutoSelect" "Debconf::Base"
"Debconf::Client::ConfModule" "Debconf::ConfModule" "Debconf::Config"
"Debconf::Db" "Debconf::DbDriver" "Debconf::DbDriver::Backup"
"Debconf::DbDriver::Cache" "Debconf::DbDriver::Copy"
"Debconf::DbDriver::Debug" "Debconf::DbDriver::DirTree"
"Debconf::DbDriver::Directory" "Debconf::DbDriver::File"
"Debconf::DbDriver::LDAP" "Debconf::DbDriver::PackageDir"
"Debconf::DbDriver::Pipe" "Debconf::DbDriver::Stack" "Debconf::Element"
"Debconf::Element::Dialog::Boolean" "Debconf::Element::Dialog::Error"
"Debconf::Element::Dialog::Multiselect" "Debconf::Element::Dialog::Note"
"Debconf::Element::Dialog::Password" "Debconf::Element::Dialog::Progress"
"Debconf::Element::Dialog::Select" "Debconf::Element::Dialog::String"
"Debconf::Element::Dialog::Text" "Debconf::Element::Editor::Boolean"
"Debconf::Element::Editor::Error" "Debconf::Element::Editor::Multiselect"
"Debconf::Element::Editor::Note" "Debconf::Element::Editor::Password"
"Debconf::Element::Editor::Progress" "Debconf::Element::Editor::Select"
"Debconf::Element::Editor::String" "Debconf::Element::Editor::Text"
"Debconf::Element::Gnome" "Debconf::Element::Gnome::Boolean"
"Debconf::Element::Gnome::Error" "Debconf::Element::Gnome::Multiselect"
"Debconf::Element::Gnome::Note" "Debconf::Element::Gnome::Password"
"Debconf::Element::Gnome::Progress" "Debconf::Element::Gnome::Select"
"Debconf::Element::Gnome::String" "Debconf::Element::Gnome::Text"
"Debconf::Element::Kde" "Debconf::Element::Kde::Boolean"
"Debconf::Element::Kde::Error" "Debconf::Element::Kde::Multiselect"
"Debconf::Element::Kde::Note" "Debconf::Element::Kde::Password"
"Debconf::Element::Kde::Progress" "Debconf::Element::Kde::Select"
"Debconf::Element::Kde::String" "Debconf::Element::Kde::Text"
"Debconf::Element::Multiselect" "Debconf::Element::Noninteractive"
"Debconf::Element::Noninteractive::Boolean"
"Debconf::Element::Noninteractive::Error"
"Debconf::Element::Noninteractive::Multiselect"
"Debconf::Element::Noninteractive::Note"
"Debconf::Element::Noninteractive::Password"
"Debconf::Element::Noninteractive::Progress"
"Debconf::Element::Noninteractive::Select"
"Debconf::Element::Noninteractive::String"
"Debconf::Element::Noninteractive::Text" "Debconf::Element::Select"
"Debconf::Element::Teletype::Boolean" "Debconf::Element::Teletype::Error"
"Debconf::Element::Teletype::Multiselect"
"Debconf::Element::Teletype::Note" "Debconf::Element::Teletype::Password"
"Debconf::Element::Teletype::Progress" "Debconf::Element::Teletype::Select"
"Debconf::Element::Teletype::String" "Debconf::Element::Teletype::Text"
"Debconf::Element::Web::Boolean" "Debconf::Element::Web::Error"
"Debconf::Element::Web::Multiselect" "Debconf::Element::Web::Note"
"Debconf::Element::Web::Password" "Debconf::Element::Web::Progress"
"Debconf::Element::Web::Select" "Debconf::Element::Web::String"
"Debconf::Element::Web::Text" "Debconf::Encoding" "Debconf::Format"
"Debconf::Format::822" "Debconf::FrontEnd" "Debconf::FrontEnd::Dialog"
"Debconf::FrontEnd::Editor" "Debconf::FrontEnd::Gnome"
"Debconf::FrontEnd::Kde" "Debconf::FrontEnd::Kde::Ui_DebconfWizard"
"Debconf::FrontEnd::Kde::Wizard" "Debconf::FrontEnd::Noninteractive"
"Debconf::FrontEnd::Passthrough" "Debconf::FrontEnd::Readline"
"Debconf::FrontEnd::ScreenSize" "Debconf::FrontEnd::Teletype"
"Debconf::FrontEnd::Text" "Debconf::FrontEnd::Web" "Debconf::Gettext"
"Debconf::Iterator" "Debconf::Log" "Debconf::Path" "Debconf::Priority"
"Debconf::Question" "Debconf::Template" "Debconf::Template::Transient"
"Debconf::TmpFile" "Debian::AdduserCommon"
"Debian::DebConf::Client::ConfModule" "Debian::Debhelper::Buildsystem"
"Debian::Debhelper::Buildsystem::ant"
"Debian::Debhelper::Buildsystem::autoconf"
"Debian::Debhelper::Buildsystem::cmake"
"Debian::Debhelper::Buildsystem::makefile"
"Debian::Debhelper::Buildsystem::perl_build"
"Debian::Debhelper::Buildsystem::perl_makemaker"
"Debian::Debhelper::Buildsystem::pybuild"
"Debian::Debhelper::Buildsystem::python_distutils"
"Debian::Debhelper::Buildsystem::qmake"
"Debian::Debhelper::Buildsystem::qmake_qt4"
"Debian::Debhelper::Dh_Buildsystems" "Debian::Debhelper::Dh_Getopt"
"Debian::Debhelper::Dh_Lib" "Debian::Debhelper::Dh_Version"
"Debian::Debhelper::Sequence::autotools_dev"
"Debian::Debhelper::Sequence::bash_completion"
"Debian::Debhelper::Sequence::pypy" "Debian::Debhelper::Sequence::python2"
"Debian::Debhelper::Sequence::python3"
"Debian::Debhelper::Sequence::python_support"
"Debian::Debhelper::Sequence::tex" "Debian::DictionariesCommon"
"Debian::DistroInfo" "Debian::DocBase::Common" "Debian::DocBase::DB"
"Debian::DocBase::DocBaseFile" "Debian::DocBase::Document"
"Debian::DocBase::Gettext" "Debian::DocBase::InstallDocs"
"Debian::DocBase::Programs::Dhelp" "Debian::DocBase::Programs::Dwww"
"Debian::DocBase::Programs::Scrollkeeper" "Debian::DocBase::Utils"
"DebianNet" "Devel::Caller" "Devel::InnerPackage" "Devel::LexAlias"
"Devel::PPPort" "Devel::Peek" "Devel::SelfStubber" "Digest" "Digest::HMAC"
"Digest::HMAC_MD5" "Digest::HMAC_SHA1" "Digest::MD5" "Digest::SHA"
"Digest::base" "Digest::file" "DirHandle" "Dpkg" "Dpkg::Arch"
"Dpkg::BuildEnv" "Dpkg::BuildFlags" "Dpkg::BuildOptions"
"Dpkg::BuildProfiles" "Dpkg::Changelog" "Dpkg::Changelog::Debian"
"Dpkg::Changelog::Entry" "Dpkg::Changelog::Entry::Debian"
"Dpkg::Changelog::Parse" "Dpkg::Checksums" "Dpkg::Compression"
"Dpkg::Compression::FileHandle" "Dpkg::Compression::Process" "Dpkg::Conf"
"Dpkg::Control" "Dpkg::Control::Changelog" "Dpkg::Control::Fields"
"Dpkg::Control::FieldsCore" "Dpkg::Control::Hash" "Dpkg::Control::HashCore"
"Dpkg::Control::Info" "Dpkg::Control::Types" "Dpkg::Deps"
"Dpkg::ErrorHandling" "Dpkg::Exit" "Dpkg::File" "Dpkg::Gettext" "Dpkg::IPC"
"Dpkg::Index" "Dpkg::Interface::Storable" "Dpkg::Package" "Dpkg::Path"
"Dpkg::Shlibs" "Dpkg::Shlibs::Cppfilt" "Dpkg::Shlibs::Objdump"
"Dpkg::Shlibs::Symbol" "Dpkg::Shlibs::SymbolFile" "Dpkg::Source::Archive"
"Dpkg::Source::Functions" "Dpkg::Source::Package"
"Dpkg::Source::Package::V1" "Dpkg::Source::Package::V2"
"Dpkg::Source::Package::V3::Bzr" "Dpkg::Source::Package::V3::Custom"
"Dpkg::Source::Package::V3::Git" "Dpkg::Source::Package::V3::Native"
"Dpkg::Source::Package::V3::Quilt" "Dpkg::Source::Patch"
"Dpkg::Source::Quilt" "Dpkg::Substvars" "Dpkg::Util" "Dpkg::Vars"
"Dpkg::Vendor" "Dpkg::Vendor::Debian" "Dpkg::Vendor::Default"
"Dpkg::Vendor::Ubuntu" "Dpkg::Version" "Dumpvalue" "DynaLoader" "EV"
"EV::MakeMaker" "EV::libev" "Email::Abstract" "Email::Abstract::EmailMIME"
"Email::Abstract::EmailSimple" "Email::Abstract::MIMEEntity"
"Email::Abstract::MailInternet" "Email::Abstract::MailMessage"
"Email::Abstract::Plugin" "Email::Address" "Email::Date"
"Email::Date::Format" "Email::Find" "Email::Find::addrspec" "Email::Simple"
"Email::Simple::Creator" "Email::Simple::Header" "Email::Valid" "Encode"
"Encode::Alias" "Encode::Byte" "Encode::CJKConstants" "Encode::CN"
"Encode::CN::HZ" "Encode::Config" "Encode::EBCDIC" "Encode::Encoder"
"Encode::Encoding" "Encode::GSM0338" "Encode::Guess" "Encode::JP"
"Encode::JP::H2Z" "Encode::JP::JIS7" "Encode::KR" "Encode::KR::2022_KR"
"Encode::Locale" "Encode::MIME::Header" "Encode::MIME::Header::ISO_2022_JP"
"Encode::MIME::Name" "Encode::PerlIO" "Encode::Supported" "Encode::Symbol"
"Encode::TW" "Encode::Unicode" "Encode::Unicode::UTF7" "English" "Env"
"Errno" "Error" "Error::Simple" "Exporter" "Exporter::Heavy"
"Exporter::Lite" "ExtUtils::CBuilder" "ExtUtils::CBuilder::Base"
"ExtUtils::CBuilder::Platform::Unix" "ExtUtils::CBuilder::Platform::VMS"
"ExtUtils::CBuilder::Platform::Windows"
"ExtUtils::CBuilder::Platform::Windows::BCC"
"ExtUtils::CBuilder::Platform::Windows::GCC"
"ExtUtils::CBuilder::Platform::Windows::MSVC"
"ExtUtils::CBuilder::Platform::aix" "ExtUtils::CBuilder::Platform::cygwin"
"ExtUtils::CBuilder::Platform::darwin"
"ExtUtils::CBuilder::Platform::dec_osf" "ExtUtils::CBuilder::Platform::os2"
"ExtUtils::Command" "ExtUtils::Command::MM" "ExtUtils::Constant"
"ExtUtils::Constant::Base" "ExtUtils::Constant::ProxySubs"
"ExtUtils::Constant::Utils" "ExtUtils::Constant::XS" "ExtUtils::Embed"
"ExtUtils::Install" "ExtUtils::Installed" "ExtUtils::Liblist"
"ExtUtils::Liblist::Kid" "ExtUtils::MM" "ExtUtils::MM_AIX"
"ExtUtils::MM_Any" "ExtUtils::MM_BeOS" "ExtUtils::MM_Cygwin"
"ExtUtils::MM_DOS" "ExtUtils::MM_Darwin" "ExtUtils::MM_MacOS"
"ExtUtils::MM_NW5" "ExtUtils::MM_OS2" "ExtUtils::MM_QNX"
"ExtUtils::MM_UWIN" "ExtUtils::MM_Unix" "ExtUtils::MM_VMS"
"ExtUtils::MM_VOS" "ExtUtils::MM_Win32" "ExtUtils::MM_Win95" "ExtUtils::MY"
"ExtUtils::MakeMaker" "ExtUtils::MakeMaker::Config"
"ExtUtils::MakeMaker::FAQ" "ExtUtils::MakeMaker::Tutorial"
"ExtUtils::Manifest" "ExtUtils::Miniperl" "ExtUtils::Mkbootstrap"
"ExtUtils::Mksymlists" "ExtUtils::Packlist" "ExtUtils::ParseXS"
"ExtUtils::ParseXS::Constants" "ExtUtils::ParseXS::CountLines"
"ExtUtils::ParseXS::Utilities" "ExtUtils::Typemaps"
"ExtUtils::Typemaps::Cmd" "ExtUtils::Typemaps::InputMap"
"ExtUtils::Typemaps::OutputMap" "ExtUtils::Typemaps::Type"
"ExtUtils::testlib" "Fatal" "Fcntl" "File::BaseDir" "File::Basename"
"File::CheckTree" "File::Compare" "File::Copy" "File::Copy::Recursive"
"File::DesktopEntry" "File::DosGlob" "File::FcntlLock" "File::Fetch"
"File::Find" "File::Glob" "File::GlobMapper" "File::HomeDir"
"File::HomeDir::Darwin" "File::HomeDir::Darwin::Carbon"
"File::HomeDir::Darwin::Cocoa" "File::HomeDir::Driver"
"File::HomeDir::FreeDesktop" "File::HomeDir::MacOS9" "File::HomeDir::Test"
"File::HomeDir::Unix" "File::HomeDir::Windows" "File::LibMagic"
"File::Listing" "File::MimeInfo" "File::MimeInfo::Applications"
"File::MimeInfo::Cookbook" "File::MimeInfo::Magic" "File::MimeInfo::Rox"
"File::Path" "File::Slurp" "File::Spec" "File::Spec::Cygwin"
"File::Spec::Epoc" "File::Spec::Functions" "File::Spec::Mac"
"File::Spec::OS2" "File::Spec::Unix" "File::Spec::VMS" "File::Spec::Win32"
"File::Temp" "File::Touch" "File::Which" "File::stat" "FileCache"
"FileHandle" "Filter::Simple" "Filter::Util::Call" "FindBin" "Font::AFM"
"Font::Metrics::Courier" "Font::Metrics::CourierBold"
"Font::Metrics::CourierBoldOblique" "Font::Metrics::CourierOblique"
"Font::Metrics::Helvetica" "Font::Metrics::HelveticaBold"
"Font::Metrics::HelveticaBoldOblique" "Font::Metrics::HelveticaOblique"
"Font::Metrics::TimesBold" "Font::Metrics::TimesBoldItalic"
"Font::Metrics::TimesItalic" "Font::Metrics::TimesRoman" "GD" "GD::Group"
"GD::Image" "GD::Polygon" "GD::Polyline" "GD::Simple" "GDBM_File"
"Getopt::Long" "Getopt::Mixed" "Getopt::Std" "Git" "Git::I18N"
"Git::IndexInfo" "Git::SVN" "Git::SVN::Editor" "Git::SVN::Fetcher"
"Git::SVN::GlobSpec" "Git::SVN::Log" "Git::SVN::Memoize::YAML"
"Git::SVN::Migration" "Git::SVN::Prompt" "Git::SVN::Ra" "Git::SVN::Utils"
"Glib" "Glib::BookmarkFile" "Glib::Boxed" "Glib::CodeGen" "Glib::Error"
"Glib::Flags" "Glib::GenPod" "Glib::Install::Files" "Glib::KeyFile"
"Glib::Log" "Glib::MainLoop" "Glib::MakeHelper" "Glib::Markup"
"Glib::Object" "Glib::Object::Subclass" "Glib::OptionContext"
"Glib::OptionGroup" "Glib::Param::Boolean" "Glib::Param::Double"
"Glib::Param::Enum" "Glib::Param::Flags" "Glib::Param::GType"
"Glib::Param::Int" "Glib::Param::Int64" "Glib::Param::String"
"Glib::Param::UInt" "Glib::Param::UInt64" "Glib::Param::Unichar"
"Glib::ParamSpec" "Glib::ParseXSDoc" "Glib::Signal" "Glib::Type"
"Glib::Utils" "Glib::devel" "Glib::index" "Glib::version" "Glib::xsapi"
"Gtk2" "Gtk2::CodeGen" "Gtk2::Gdk::Keysyms" "Gtk2::Helper"
"Gtk2::Install::Files" "Gtk2::Pango" "Gtk2::SimpleList" "Gtk2::SimpleMenu"
"Gtk2::TestHelper" "Guard" "HTML::AsSubs" "HTML::Element"
"HTML::Element::traverse" "HTML::Entities" "HTML::Filter" "HTML::Form"
"HTML::FormatMarkdown" "HTML::FormatPS" "HTML::FormatRTF"
"HTML::FormatText" "HTML::Formatter" "HTML::HeadParser" "HTML::LinkExtor"
"HTML::Parse" "HTML::Parser" "HTML::PullParser" "HTML::Tagset"
"HTML::TokeParser" "HTML::Tree" "HTML::Tree::AboutObjects"
"HTML::Tree::AboutTrees" "HTML::Tree::Scanning" "HTML::TreeBuilder"
"HTTP::Config" "HTTP::Cookies" "HTTP::Cookies::Microsoft"
"HTTP::Cookies::Netscape" "HTTP::Daemon" "HTTP::Date" "HTTP::Headers"
"HTTP::Headers::Auth" "HTTP::Headers::ETag" "HTTP::Headers::Util"
"HTTP::Message" "HTTP::Negotiate" "HTTP::Request" "HTTP::Request::Common"
"HTTP::Response" "HTTP::Status" "HTTP::Tiny" "Hash::Util"
"Hash::Util::FieldHash" "I18N::Collate" "I18N::LangTags"
"I18N::LangTags::Detect" "I18N::LangTags::List" "I18N::Langinfo" "IO"
"IO::AtomicFile" "IO::Compress::Adapter::Bzip2"
"IO::Compress::Adapter::Deflate" "IO::Compress::Adapter::Identity"
"IO::Compress::Base" "IO::Compress::Base::Common" "IO::Compress::Bzip2"
"IO::Compress::Deflate" "IO::Compress::FAQ" "IO::Compress::Gzip"
"IO::Compress::Gzip::Constants" "IO::Compress::RawDeflate"
"IO::Compress::Zip" "IO::Compress::Zip::Constants"
"IO::Compress::Zlib::Constants" "IO::Compress::Zlib::Extra" "IO::Dir"
"IO::File" "IO::HTML" "IO::Handle" "IO::InnerFile" "IO::Lines" "IO::Pipe"
"IO::Poll" "IO::Pty" "IO::Scalar" "IO::ScalarArray" "IO::Seekable"
"IO::Select" "IO::Socket" "IO::Socket::INET" "IO::Socket::INET6"
"IO::Socket::SSL" "IO::Socket::SSL::Intercept" "IO::Socket::SSL::Utils"
"IO::Socket::UNIX" "IO::String" "IO::Stringy" "IO::Tty" "IO::Tty::Constant"
"IO::Uncompress::Adapter::Bunzip2" "IO::Uncompress::Adapter::Identity"
"IO::Uncompress::Adapter::Inflate" "IO::Uncompress::AnyInflate"
"IO::Uncompress::AnyUncompress" "IO::Uncompress::Base"
"IO::Uncompress::Bunzip2" "IO::Uncompress::Gunzip"
"IO::Uncompress::Inflate" "IO::Uncompress::RawInflate"
"IO::Uncompress::Unzip" "IO::Wrap" "IO::WrapTie" "IO::Zlib" "IPC::Cmd"
"IPC::Msg" "IPC::Open2" "IPC::Open3" "IPC::Run" "IPC::Run::Debug"
"IPC::Run::IO" "IPC::Run::Timer" "IPC::Semaphore" "IPC::SharedMem"
"IPC::SysV" "IPC::System::Simple" "JSON" "JSON::PP" "JSON::PP::Boolean"
"JSON::XS" "JSON::XS::Boolean" "JSON::backportPP"
"JSON::backportPP::Boolean" "JSON::backportPP::Compat5005"
"JSON::backportPP::Compat5006" "LWP" "LWP::Authen::Basic"
"LWP::Authen::Digest" "LWP::Authen::Ntlm" "LWP::ConnCache" "LWP::Debug"
"LWP::DebugFile" "LWP::MediaTypes" "LWP::MemberMixin" "LWP::Protocol"
"LWP::Protocol::GHTTP" "LWP::Protocol::cpan" "LWP::Protocol::data"
"LWP::Protocol::file" "LWP::Protocol::ftp" "LWP::Protocol::gopher"
"LWP::Protocol::http" "LWP::Protocol::https" "LWP::Protocol::loopback"
"LWP::Protocol::mailto" "LWP::Protocol::nntp" "LWP::Protocol::nogo"
"LWP::RobotUA" "LWP::Simple" "LWP::UserAgent" "Lexical::Persistence"
"LibAppArmor" "Lintian::Architecture" "Lintian::Check"
"Lintian::CheckScript" "Lintian::CollScript" "Lintian::Collect"
"Lintian::Collect::Binary" "Lintian::Collect::Changes"
"Lintian::Collect::Group" "Lintian::Collect::Package"
"Lintian::Collect::Source" "Lintian::Command" "Lintian::Command::Simple"
"Lintian::Data" "Lintian::DepMap" "Lintian::DepMap::Properties"
"Lintian::Internal::FrontendUtil" "Lintian::Lab" "Lintian::Lab::Entry"
"Lintian::Lab::Manifest" "Lintian::Lab::ManifestDiff" "Lintian::Output"
"Lintian::Output::ColonSeparated" "Lintian::Output::FullEWI"
"Lintian::Output::LetterQualifier" "Lintian::Output::XML" "Lintian::Path"
"Lintian::Processable" "Lintian::Processable::Package"
"Lintian::ProcessableGroup" "Lintian::ProcessablePool" "Lintian::Profile"
"Lintian::Relation" "Lintian::Relation::Version"
"Lintian::Reporting::ResourceManager" "Lintian::SlidingWindow"
"Lintian::Tag::Info" "Lintian::Tag::Override" "Lintian::Tag::TextUtil"
"Lintian::Tags" "Lintian::Unpacker" "Lintian::Util" "List::MoreUtils"
"List::Util" "List::Util::XS" "Locale::Codes" "Locale::Codes::API"
"Locale::Codes::Changes" "Locale::Codes::Constants"
"Locale::Codes::Country" "Locale::Codes::Country_Codes"
"Locale::Codes::Country_Retired" "Locale::Codes::Currency"
"Locale::Codes::Currency_Codes" "Locale::Codes::Currency_Retired"
"Locale::Codes::LangExt" "Locale::Codes::LangExt_Codes"
"Locale::Codes::LangExt_Retired" "Locale::Codes::LangFam"
"Locale::Codes::LangFam_Codes" "Locale::Codes::LangFam_Retired"
"Locale::Codes::LangVar" "Locale::Codes::LangVar_Codes"
"Locale::Codes::LangVar_Retired" "Locale::Codes::Language"
"Locale::Codes::Language_Codes" "Locale::Codes::Language_Retired"
"Locale::Codes::Script" "Locale::Codes::Script_Codes"
"Locale::Codes::Script_Retired" "Locale::Country" "Locale::Currency"
"Locale::Language" "Locale::Maketext" "Locale::Maketext::Cookbook"
"Locale::Maketext::Guts" "Locale::Maketext::GutsLoader"
"Locale::Maketext::Simple" "Locale::Maketext::TPJ13" "Locale::Messages"
"Locale::Recode" "Locale::Recode::_Aliases" "Locale::Recode::_Conversions"
"Locale::RecodeData" "Locale::RecodeData::ASMO_449"
"Locale::RecodeData::ATARI_ST" "Locale::RecodeData::ATARI_ST_EURO"
"Locale::RecodeData::CP10007" "Locale::RecodeData::CP1250"
"Locale::RecodeData::CP1251" "Locale::RecodeData::CP1252"
"Locale::RecodeData::CP1253" "Locale::RecodeData::CP1254"
"Locale::RecodeData::CP1256" "Locale::RecodeData::CP1257"
"Locale::RecodeData::CSN_369103" "Locale::RecodeData::CWI"
"Locale::RecodeData::DEC_MCS" "Locale::RecodeData::EBCDIC_AT_DE"
"Locale::RecodeData::EBCDIC_AT_DE_A" "Locale::RecodeData::EBCDIC_CA_FR"
"Locale::RecodeData::EBCDIC_DK_NO" "Locale::RecodeData::EBCDIC_DK_NO_A"
"Locale::RecodeData::EBCDIC_ES" "Locale::RecodeData::EBCDIC_ES_A"
"Locale::RecodeData::EBCDIC_ES_S" "Locale::RecodeData::EBCDIC_FI_SE"
"Locale::RecodeData::EBCDIC_FI_SE_A" "Locale::RecodeData::EBCDIC_FR"
"Locale::RecodeData::EBCDIC_IS_FRISS" "Locale::RecodeData::EBCDIC_IT"
"Locale::RecodeData::EBCDIC_PT" "Locale::RecodeData::EBCDIC_UK"
"Locale::RecodeData::EBCDIC_US" "Locale::RecodeData::ECMA_CYRILLIC"
"Locale::RecodeData::GEORGIAN_ACADEMY" "Locale::RecodeData::GEORGIAN_PS"
"Locale::RecodeData::GOST_19768_74" "Locale::RecodeData::GREEK7"
"Locale::RecodeData::GREEK7_OLD" "Locale::RecodeData::GREEK_CCITT"
"Locale::RecodeData::HP_ROMAN8" "Locale::RecodeData::IBM037"
"Locale::RecodeData::IBM038" "Locale::RecodeData::IBM1004"
"Locale::RecodeData::IBM1026" "Locale::RecodeData::IBM1047"
"Locale::RecodeData::IBM256" "Locale::RecodeData::IBM273"
"Locale::RecodeData::IBM274" "Locale::RecodeData::IBM275"
"Locale::RecodeData::IBM277" "Locale::RecodeData::IBM278"
"Locale::RecodeData::IBM280" "Locale::RecodeData::IBM281"
"Locale::RecodeData::IBM284" "Locale::RecodeData::IBM285"
"Locale::RecodeData::IBM290" "Locale::RecodeData::IBM297"
"Locale::RecodeData::IBM420" "Locale::RecodeData::IBM423"
"Locale::RecodeData::IBM424" "Locale::RecodeData::IBM437"
"Locale::RecodeData::IBM500" "Locale::RecodeData::IBM850"
"Locale::RecodeData::IBM851" "Locale::RecodeData::IBM852"
"Locale::RecodeData::IBM855" "Locale::RecodeData::IBM857"
"Locale::RecodeData::IBM860" "Locale::RecodeData::IBM861"
"Locale::RecodeData::IBM862" "Locale::RecodeData::IBM863"
"Locale::RecodeData::IBM864" "Locale::RecodeData::IBM865"
"Locale::RecodeData::IBM866" "Locale::RecodeData::IBM868"
"Locale::RecodeData::IBM869" "Locale::RecodeData::IBM870"
"Locale::RecodeData::IBM871" "Locale::RecodeData::IBM874"
"Locale::RecodeData::IBM875" "Locale::RecodeData::IBM880"
"Locale::RecodeData::IBM891" "Locale::RecodeData::IBM903"
"Locale::RecodeData::IBM904" "Locale::RecodeData::IBM905"
"Locale::RecodeData::IBM918" "Locale::RecodeData::IEC_P27_1"
"Locale::RecodeData::INIS" "Locale::RecodeData::INIS_8"
"Locale::RecodeData::INIS_CYRILLIC" "Locale::RecodeData::ISO_10367_BOX"
"Locale::RecodeData::ISO_2033_1983" "Locale::RecodeData::ISO_5427"
"Locale::RecodeData::ISO_5427_EXT" "Locale::RecodeData::ISO_5428"
"Locale::RecodeData::ISO_8859_1" "Locale::RecodeData::ISO_8859_10"
"Locale::RecodeData::ISO_8859_11" "Locale::RecodeData::ISO_8859_13"
"Locale::RecodeData::ISO_8859_14" "Locale::RecodeData::ISO_8859_15"
"Locale::RecodeData::ISO_8859_16" "Locale::RecodeData::ISO_8859_2"
"Locale::RecodeData::ISO_8859_3" "Locale::RecodeData::ISO_8859_4"
"Locale::RecodeData::ISO_8859_5" "Locale::RecodeData::ISO_8859_6"
"Locale::RecodeData::ISO_8859_7" "Locale::RecodeData::ISO_8859_8"
"Locale::RecodeData::ISO_8859_9" "Locale::RecodeData::KOI8_R"
"Locale::RecodeData::KOI8_RU" "Locale::RecodeData::KOI8_T"
"Locale::RecodeData::KOI8_U" "Locale::RecodeData::KOI_8"
"Locale::RecodeData::LATIN_GREEK" "Locale::RecodeData::LATIN_GREEK_1"
"Locale::RecodeData::MACARABIC" "Locale::RecodeData::MACCROATIAN"
"Locale::RecodeData::MACCYRILLIC" "Locale::RecodeData::MACGREEK"
"Locale::RecodeData::MACHEBREW" "Locale::RecodeData::MACICELAND"
"Locale::RecodeData::MACINTOSH" "Locale::RecodeData::MACROMANIA"
"Locale::RecodeData::MACTHAI" "Locale::RecodeData::MACTURKISH"
"Locale::RecodeData::MACUKRAINE" "Locale::RecodeData::MAC_IS"
"Locale::RecodeData::MAC_SAMI" "Locale::RecodeData::MAC_UK"
"Locale::RecodeData::NATS_DANO" "Locale::RecodeData::NATS_SEFI"
"Locale::RecodeData::NEXTSTEP" "Locale::RecodeData::SAMI_WS2"
"Locale::RecodeData::TIS_620" "Locale::RecodeData::US_ASCII"
"Locale::RecodeData::UTF_8" "Locale::RecodeData::VISCII"
"Locale::RecodeData::_Encode" "Locale::Script" "Locale::TextDomain"
"Locale::Util" "Locale::gettext" "Locale::gettext_dumb"
"Locale::gettext_pp" "Locale::libintlFAQ" "Log::Log4perl"
"Log::Log4perl::Appender" "Log::Log4perl::Appender::Buffer"
"Log::Log4perl::Appender::DBI" "Log::Log4perl::Appender::File"
"Log::Log4perl::Appender::Limit" "Log::Log4perl::Appender::RRDs"
"Log::Log4perl::Appender::Screen"
"Log::Log4perl::Appender::ScreenColoredLevels"
"Log::Log4perl::Appender::Socket" "Log::Log4perl::Appender::String"
"Log::Log4perl::Appender::Synchronized"
"Log::Log4perl::Appender::TestArrayBuffer"
"Log::Log4perl::Appender::TestBuffer"
"Log::Log4perl::Appender::TestFileCreeper" "Log::Log4perl::Catalyst"
"Log::Log4perl::Config" "Log::Log4perl::Config::BaseConfigurator"
"Log::Log4perl::Config::DOMConfigurator"
"Log::Log4perl::Config::PropertyConfigurator"
"Log::Log4perl::Config::Watch" "Log::Log4perl::DateFormat"
"Log::Log4perl::FAQ" "Log::Log4perl::Filter"
"Log::Log4perl::Filter::Boolean" "Log::Log4perl::Filter::LevelMatch"
"Log::Log4perl::Filter::LevelRange" "Log::Log4perl::Filter::MDC"
"Log::Log4perl::Filter::StringMatch" "Log::Log4perl::InternalDebug"
"Log::Log4perl::JavaMap" "Log::Log4perl::JavaMap::ConsoleAppender"
"Log::Log4perl::JavaMap::FileAppender"
"Log::Log4perl::JavaMap::JDBCAppender"
"Log::Log4perl::JavaMap::NTEventLogAppender"
"Log::Log4perl::JavaMap::RollingFileAppender"
"Log::Log4perl::JavaMap::SyslogAppender"
"Log::Log4perl::JavaMap::TestBuffer" "Log::Log4perl::Layout"
"Log::Log4perl::Layout::NoopLayout" "Log::Log4perl::Layout::PatternLayout"
"Log::Log4perl::Layout::PatternLayout::Multiline"
"Log::Log4perl::Layout::SimpleLayout" "Log::Log4perl::Level"
"Log::Log4perl::Logger" "Log::Log4perl::MDC" "Log::Log4perl::NDC"
"Log::Log4perl::Resurrector" "Log::Log4perl::Util"
"Log::Log4perl::Util::Semaphore" "Log::Log4perl::Util::TimeTracker"
"Log::Message" "Log::Message::Config" "Log::Message::Handlers"
"Log::Message::Item" "Log::Message::Simple" "MIME::Base64" "MIME::Body"
"MIME::Decoder" "MIME::Decoder::Base64" "MIME::Decoder::BinHex"
"MIME::Decoder::Binary" "MIME::Decoder::Gzip64" "MIME::Decoder::NBit"
"MIME::Decoder::QuotedPrint" "MIME::Decoder::UU" "MIME::Entity"
"MIME::Field::ConTraEnc" "MIME::Field::ContDisp" "MIME::Field::ContType"
"MIME::Field::ParamVal" "MIME::Head" "MIME::Parser" "MIME::Parser::Filer"
"MIME::Parser::Reader" "MIME::Parser::Results" "MIME::QuotedPrint"
"MIME::Tools" "MIME::Type" "MIME::Types" "MIME::WordDecoder" "MIME::Words"
"MRO::Compat" "Mail::Address" "Mail::Cap" "Mail::Field"
"Mail::Field::AddrList" "Mail::Field::Date" "Mail::Field::Generic"
"Mail::Filter" "Mail::Header" "Mail::Internet" "Mail::Mailer"
"Mail::Mailer::qmail" "Mail::Mailer::rfc822" "Mail::Mailer::sendmail"
"Mail::Mailer::smtp" "Mail::Mailer::smtps" "Mail::Mailer::testfile"
"Mail::Send" "Mail::Sendmail" "Mail::Util" "Math::BigFloat"
"Math::BigFloat::Trace" "Math::BigInt" "Math::BigInt::Calc"
"Math::BigInt::CalcEmu" "Math::BigInt::FastCalc" "Math::BigInt::Trace"
"Math::BigRat" "Math::Complex" "Math::Trig" "Memoize"
"Memoize::AnyDBM_File" "Memoize::Expire" "Memoize::ExpireFile"
"Memoize::ExpireTest" "Memoize::NDBM_File" "Memoize::SDBM_File"
"Memoize::Storable" "Module::Build" "Module::Build::API"
"Module::Build::Authoring" "Module::Build::Base" "Module::Build::Bundling"
"Module::Build::Compat" "Module::Build::Config" "Module::Build::ConfigData"
"Module::Build::Cookbook" "Module::Build::Dumper"
"Module::Build::ModuleInfo" "Module::Build::Notes"
"Module::Build::PPMMaker" "Module::Build::Platform::Amiga"
"Module::Build::Platform::Default" "Module::Build::Platform::EBCDIC"
"Module::Build::Platform::MPEiX" "Module::Build::Platform::MacOS"
"Module::Build::Platform::RiscOS" "Module::Build::Platform::Unix"
"Module::Build::Platform::VMS" "Module::Build::Platform::VOS"
"Module::Build::Platform::Windows" "Module::Build::Platform::aix"
"Module::Build::Platform::cygwin" "Module::Build::Platform::darwin"
"Module::Build::Platform::os2" "Module::Build::PodParser"
"Module::Build::Version" "Module::Build::YAML" "Module::CoreList"
"Module::CoreList::TieHashDelta" "Module::CoreList::Utils"
"Module::Implementation" "Module::Load" "Module::Load::Conditional"
"Module::Loaded" "Module::Metadata" "Module::Pluggable"
"Module::Pluggable::Object" "Module::Refresh" "Module::Runtime" "NDBM_File"
"NEXT" "Net::Cmd" "Net::Config" "Net::DNS" "Net::DNS::Domain"
"Net::DNS::DomainName" "Net::DNS::FAQ" "Net::DNS::Header"
"Net::DNS::Mailbox" "Net::DNS::Nameserver" "Net::DNS::Packet"
"Net::DNS::Question" "Net::DNS::RR" "Net::DNS::RR::A" "Net::DNS::RR::AAAA"
"Net::DNS::RR::AFSDB" "Net::DNS::RR::APL" "Net::DNS::RR::APL::ApItem"
"Net::DNS::RR::CERT" "Net::DNS::RR::CNAME" "Net::DNS::RR::DHCID"
"Net::DNS::RR::DNAME" "Net::DNS::RR::EID" "Net::DNS::RR::HINFO"
"Net::DNS::RR::HIP" "Net::DNS::RR::IPSECKEY" "Net::DNS::RR::ISDN"
"Net::DNS::RR::KX" "Net::DNS::RR::LOC" "Net::DNS::RR::MB"
"Net::DNS::RR::MG" "Net::DNS::RR::MINFO" "Net::DNS::RR::MR"
"Net::DNS::RR::MX" "Net::DNS::RR::NAPTR" "Net::DNS::RR::NIMLOC"
"Net::DNS::RR::NS" "Net::DNS::RR::NSAP" "Net::DNS::RR::NULL"
"Net::DNS::RR::OPT" "Net::DNS::RR::PTR" "Net::DNS::RR::PX"
"Net::DNS::RR::RP" "Net::DNS::RR::RT" "Net::DNS::RR::SOA"
"Net::DNS::RR::SPF" "Net::DNS::RR::SRV" "Net::DNS::RR::SSHFP"
"Net::DNS::RR::TKEY" "Net::DNS::RR::TSIG" "Net::DNS::RR::TXT"
"Net::DNS::RR::Unknown" "Net::DNS::RR::X25" "Net::DNS::Resolver"
"Net::DNS::Resolver::Base" "Net::DNS::Resolver::Cygwin"
"Net::DNS::Resolver::Recurse" "Net::DNS::Resolver::UNIX"
"Net::DNS::Resolver::Win32" "Net::DNS::Text" "Net::DNS::Update"
"Net::Domain" "Net::Domain::TLD" "Net::FTP" "Net::FTP::A" "Net::FTP::E"
"Net::FTP::I" "Net::FTP::L" "Net::FTP::dataconn" "Net::HTTP"
"Net::HTTP::Methods" "Net::HTTP::NB" "Net::HTTPS" "Net::IP" "Net::LibIDN"
"Net::NNTP" "Net::Netrc" "Net::POP3" "Net::Ping" "Net::SMTP"
"Net::SMTP::SSL" "Net::SSLeay" "Net::SSLeay::Handle" "Net::Time"
"Net::hostent" "Net::libnetFAQ" "Net::netent" "Net::protoent"
"Net::servent" "O" "ODBM_File" "Object::Accessor" "Opcode" "POSIX"
"Package::Constants" "Package::Stash" "Package::Stash::PP"
"Package::Stash::XS" "PadWalker" "Pango" "Pango::AttrBackground"
"Pango::AttrColor" "Pango::AttrFallback" "Pango::AttrFamily"
"Pango::AttrFontDesc" "Pango::AttrForeground" "Pango::AttrGravity"
"Pango::AttrGravityHint" "Pango::AttrInt" "Pango::AttrIterator"
"Pango::AttrLanguage" "Pango::AttrLetterSpacing" "Pango::AttrList"
"Pango::AttrRise" "Pango::AttrScale" "Pango::AttrShape" "Pango::AttrSize"
"Pango::AttrStretch" "Pango::AttrStrikethrough"
"Pango::AttrStrikethroughColor" "Pango::AttrString" "Pango::AttrStyle"
"Pango::AttrUnderline" "Pango::AttrUnderlineColor" "Pango::AttrVariant"
"Pango::AttrWeight" "Pango::Attribute" "Pango::Cairo"
"Pango::Cairo::Context" "Pango::Cairo::Font" "Pango::Cairo::FontMap"
"Pango::Color" "Pango::Context" "Pango::Font" "Pango::FontDescription"
"Pango::FontFace" "Pango::FontFamily" "Pango::FontMap" "Pango::FontMetrics"
"Pango::Fontset" "Pango::Gravity" "Pango::Install::Files" "Pango::Language"
"Pango::Layout" "Pango::LayoutIter" "Pango::LayoutLine" "Pango::Matrix"
"Pango::Renderer" "Pango::Script" "Pango::ScriptIter" "Pango::TabArray"
"Pango::index" "Pango::version" "Params::Check" "Params::Classify"
"Params::Util" "Params::Validate" "Params::Validate::Constants"
"Params::Validate::PP" "Params::Validate::XS" "Params::ValidatePP"
"Params::ValidateXS" "Parse::CPAN::Meta" "Parse::DebControl"
"Parse::DebControl::Error" "Parse::DebControl::Patch"
"Parse::DebianChangelog" "Parse::DebianChangelog::ChangesFilters"
"Parse::DebianChangelog::Entry" "Parse::DebianChangelog::Util"
"Perl::OSType" "PerlConsole" "PerlConsole::Commands" "PerlConsole::Console"
"PerlConsole::Preferences" "PerlIO" "PerlIO::encoding" "PerlIO::gzip"
"PerlIO::mmap" "PerlIO::scalar" "PerlIO::via" "PerlIO::via::QuotedPrint"
"Perldoc::Search" "Pod::Checker" "Pod::Escapes" "Pod::Find"
"Pod::Functions" "Pod::Html" "Pod::InputObjects" "Pod::LaTeX" "Pod::Man"
"Pod::ParseLink" "Pod::ParseUtils" "Pod::Parser" "Pod::Perldoc"
"Pod::Perldoc::BaseTo" "Pod::Perldoc::GetOptsOO" "Pod::Perldoc::ToANSI"
"Pod::Perldoc::ToChecker" "Pod::Perldoc::ToMan" "Pod::Perldoc::ToNroff"
"Pod::Perldoc::ToPod" "Pod::Perldoc::ToRtf" "Pod::Perldoc::ToTerm"
"Pod::Perldoc::ToText" "Pod::Perldoc::ToTk" "Pod::Perldoc::ToXml"
"Pod::PlainText" "Pod::Select" "Pod::Simple" "Pod::Simple::BlackBox"
"Pod::Simple::Checker" "Pod::Simple::Debug" "Pod::Simple::DumpAsText"
"Pod::Simple::DumpAsXML" "Pod::Simple::HTML" "Pod::Simple::HTMLBatch"
"Pod::Simple::HTMLLegacy" "Pod::Simple::LinkSection" "Pod::Simple::Methody"
"Pod::Simple::Progress" "Pod::Simple::PullParser"
"Pod::Simple::PullParserEndToken" "Pod::Simple::PullParserStartToken"
"Pod::Simple::PullParserTextToken" "Pod::Simple::PullParserToken"
"Pod::Simple::RTF" "Pod::Simple::Search" "Pod::Simple::SimpleTree"
"Pod::Simple::Subclassing" "Pod::Simple::Text" "Pod::Simple::TextContent"
"Pod::Simple::TiedOutFH" "Pod::Simple::Transcode"
"Pod::Simple::TranscodeDumb" "Pod::Simple::TranscodeSmart"
"Pod::Simple::XHTML" "Pod::Simple::XMLOutStream" "Pod::Text"
"Pod::Text::Color" "Pod::Text::Overstrike" "Pod::Text::Termcap"
"Pod::Usage" "Pod::UsageTrans" "SDBM_File" "SGMLS" "SGMLS::Output"
"SGMLS::Refs" "SVN::Base" "SVN::Client" "SVN::Core" "SVN::Delta" "SVN::Fs"
"SVN::Ra" "SVN::Repos" "SVN::Wc" "SWISH::API" "SWISH::API::Common" "Safe"
"Scalar::Util" "Search::Dict" "SelectSaver" "SelfLoader"
"Shell::POSIX::Select" "Socket" "Socket6" "Storable" "Sub::Identify"
"Sub::Install" "Sub::Name" "Symbol" "Sys::Hostname" "Sys::Hostname::Long"
"Sys::Syslog" "Sysadm::Install" "TAP::Base" "TAP::Formatter::Base"
"TAP::Formatter::Color" "TAP::Formatter::Console"
"TAP::Formatter::Console::ParallelSession"
"TAP::Formatter::Console::Session" "TAP::Formatter::File"
"TAP::Formatter::File::Session" "TAP::Formatter::Session" "TAP::Harness"
"TAP::Harness::Beyond" "TAP::Object" "TAP::Parser"
"TAP::Parser::Aggregator" "TAP::Parser::Grammar" "TAP::Parser::Iterator"
"TAP::Parser::Iterator::Array" "TAP::Parser::Iterator::Process"
"TAP::Parser::Iterator::Stream" "TAP::Parser::IteratorFactory"
"TAP::Parser::Multiplexer" "TAP::Parser::Result"
"TAP::Parser::Result::Bailout" "TAP::Parser::Result::Comment"
"TAP::Parser::Result::Plan" "TAP::Parser::Result::Pragma"
"TAP::Parser::Result::Test" "TAP::Parser::Result::Unknown"
"TAP::Parser::Result::Version" "TAP::Parser::Result::YAML"
"TAP::Parser::ResultFactory" "TAP::Parser::Scheduler"
"TAP::Parser::Scheduler::Job" "TAP::Parser::Scheduler::Spinner"
"TAP::Parser::Source" "TAP::Parser::SourceHandler"
"TAP::Parser::SourceHandler::Executable" "TAP::Parser::SourceHandler::File"
"TAP::Parser::SourceHandler::Handle" "TAP::Parser::SourceHandler::Perl"
"TAP::Parser::SourceHandler::RawTAP" "TAP::Parser::Utils"
"TAP::Parser::YAMLish::Reader" "TAP::Parser::YAMLish::Writer" "Template"
"Template::Base" "Template::Config" "Template::Constants"
"Template::Context" "Template::Directive" "Template::Document"
"Template::Exception" "Template::FAQ" "Template::Filters"
"Template::Grammar" "Template::Iterator" "Template::Manual"
"Template::Manual::Config" "Template::Manual::Credits"
"Template::Manual::Directives" "Template::Manual::Filters"
"Template::Manual::Internals" "Template::Manual::Intro"
"Template::Manual::Plugins" "Template::Manual::Syntax"
"Template::Manual::VMethods" "Template::Manual::Variables"
"Template::Manual::Views" "Template::Modules"
"Template::Namespace::Constants" "Template::Parser" "Template::Plugin"
"Template::Plugin::Assert" "Template::Plugin::CGI"
"Template::Plugin::Datafile" "Template::Plugin::Date"
"Template::Plugin::Directory" "Template::Plugin::Dumper"
"Template::Plugin::File" "Template::Plugin::Filter"
"Template::Plugin::Format" "Template::Plugin::HTML"
"Template::Plugin::Image" "Template::Plugin::Iterator"
"Template::Plugin::Math" "Template::Plugin::Pod"
"Template::Plugin::Procedural" "Template::Plugin::Scalar"
"Template::Plugin::String" "Template::Plugin::Table"
"Template::Plugin::URL" "Template::Plugin::View" "Template::Plugin::Wrap"
"Template::Plugins" "Template::Provider" "Template::Service"
"Template::Stash" "Template::Stash::Context" "Template::Stash::XS"
"Template::Test" "Template::Toolkit" "Template::Tools"
"Template::Tools::tpage" "Template::Tools::ttree" "Template::Tutorial"
"Template::Tutorial::Datafile" "Template::Tutorial::Web"
"Template::VMethods" "Template::View" "Term::ANSIColor" "Term::Cap"
"Term::Complete" "Term::ReadKey" "Term::ReadLine" "Term::ReadLine::Gnu"
"Term::ReadLine::Gnu::XS" "Term::UI" "Term::UI::History" "Test"
"Test::Builder" "Test::Builder::Module" "Test::Builder::Tester"
"Test::Builder::Tester::Color" "Test::Harness" "Test::More" "Test::Simple"
"Test::Tutorial" "Text::Abbrev" "Text::Balanced" "Text::CharWidth"
"Text::Iconv" "Text::Levenshtein" "Text::ParseWords" "Text::Soundex"
"Text::Tabs" "Text::Unidecode" "Text::Unidecode::x00"
"Text::Unidecode::x01" "Text::Unidecode::x02" "Text::Unidecode::x03"
"Text::Unidecode::x04" "Text::Unidecode::x05" "Text::Unidecode::x06"
"Text::Unidecode::x07" "Text::Unidecode::x09" "Text::Unidecode::x0a"
"Text::Unidecode::x0b" "Text::Unidecode::x0c" "Text::Unidecode::x0d"
"Text::Unidecode::x0e" "Text::Unidecode::x0f" "Text::Unidecode::x10"
"Text::Unidecode::x11" "Text::Unidecode::x12" "Text::Unidecode::x13"
"Text::Unidecode::x14" "Text::Unidecode::x15" "Text::Unidecode::x16"
"Text::Unidecode::x17" "Text::Unidecode::x18" "Text::Unidecode::x1e"
"Text::Unidecode::x1f" "Text::Unidecode::x20" "Text::Unidecode::x21"
"Text::Unidecode::x22" "Text::Unidecode::x23" "Text::Unidecode::x24"
"Text::Unidecode::x25" "Text::Unidecode::x26" "Text::Unidecode::x27"
"Text::Unidecode::x28" "Text::Unidecode::x2e" "Text::Unidecode::x2f"
"Text::Unidecode::x30" "Text::Unidecode::x31" "Text::Unidecode::x32"
"Text::Unidecode::x33" "Text::Unidecode::x4d" "Text::Unidecode::x4e"
"Text::Unidecode::x4f" "Text::Unidecode::x50" "Text::Unidecode::x51"
"Text::Unidecode::x52" "Text::Unidecode::x53" "Text::Unidecode::x54"
"Text::Unidecode::x55" "Text::Unidecode::x56" "Text::Unidecode::x57"
"Text::Unidecode::x58" "Text::Unidecode::x59" "Text::Unidecode::x5a"
"Text::Unidecode::x5b" "Text::Unidecode::x5c" "Text::Unidecode::x5d"
"Text::Unidecode::x5e" "Text::Unidecode::x5f" "Text::Unidecode::x60"
"Text::Unidecode::x61" "Text::Unidecode::x62" "Text::Unidecode::x63"
"Text::Unidecode::x64" "Text::Unidecode::x65" "Text::Unidecode::x66"
"Text::Unidecode::x67" "Text::Unidecode::x68" "Text::Unidecode::x69"
"Text::Unidecode::x6a" "Text::Unidecode::x6b" "Text::Unidecode::x6c"
"Text::Unidecode::x6d" "Text::Unidecode::x6e" "Text::Unidecode::x6f"
"Text::Unidecode::x70" "Text::Unidecode::x71" "Text::Unidecode::x72"
"Text::Unidecode::x73" "Text::Unidecode::x74" "Text::Unidecode::x75"
"Text::Unidecode::x76" "Text::Unidecode::x77" "Text::Unidecode::x78"
"Text::Unidecode::x79" "Text::Unidecode::x7a" "Text::Unidecode::x7b"
"Text::Unidecode::x7c" "Text::Unidecode::x7d" "Text::Unidecode::x7e"
"Text::Unidecode::x7f" "Text::Unidecode::x80" "Text::Unidecode::x81"
"Text::Unidecode::x82" "Text::Unidecode::x83" "Text::Unidecode::x84"
"Text::Unidecode::x85" "Text::Unidecode::x86" "Text::Unidecode::x87"
"Text::Unidecode::x88" "Text::Unidecode::x89" "Text::Unidecode::x8a"
"Text::Unidecode::x8b" "Text::Unidecode::x8c" "Text::Unidecode::x8d"
"Text::Unidecode::x8e" "Text::Unidecode::x8f" "Text::Unidecode::x90"
"Text::Unidecode::x91" "Text::Unidecode::x92" "Text::Unidecode::x93"
"Text::Unidecode::x94" "Text::Unidecode::x95" "Text::Unidecode::x96"
"Text::Unidecode::x97" "Text::Unidecode::x98" "Text::Unidecode::x99"
"Text::Unidecode::x9a" "Text::Unidecode::x9b" "Text::Unidecode::x9c"
"Text::Unidecode::x9d" "Text::Unidecode::x9e" "Text::Unidecode::x9f"
"Text::Unidecode::xa0" "Text::Unidecode::xa1" "Text::Unidecode::xa2"
"Text::Unidecode::xa3" "Text::Unidecode::xa4" "Text::Unidecode::xac"
"Text::Unidecode::xad" "Text::Unidecode::xae" "Text::Unidecode::xaf"
"Text::Unidecode::xb0" "Text::Unidecode::xb1" "Text::Unidecode::xb2"
"Text::Unidecode::xb3" "Text::Unidecode::xb4" "Text::Unidecode::xb5"
"Text::Unidecode::xb6" "Text::Unidecode::xb7" "Text::Unidecode::xb8"
"Text::Unidecode::xb9" "Text::Unidecode::xba" "Text::Unidecode::xbb"
"Text::Unidecode::xbc" "Text::Unidecode::xbd" "Text::Unidecode::xbe"
"Text::Unidecode::xbf" "Text::Unidecode::xc0" "Text::Unidecode::xc1"
"Text::Unidecode::xc2" "Text::Unidecode::xc3" "Text::Unidecode::xc4"
"Text::Unidecode::xc5" "Text::Unidecode::xc6" "Text::Unidecode::xc7"
"Text::Unidecode::xc8" "Text::Unidecode::xc9" "Text::Unidecode::xca"
"Text::Unidecode::xcb" "Text::Unidecode::xcc" "Text::Unidecode::xcd"
"Text::Unidecode::xce" "Text::Unidecode::xcf" "Text::Unidecode::xd0"
"Text::Unidecode::xd1" "Text::Unidecode::xd2" "Text::Unidecode::xd3"
"Text::Unidecode::xd4" "Text::Unidecode::xd5" "Text::Unidecode::xd6"
"Text::Unidecode::xd7" "Text::Unidecode::xf9" "Text::Unidecode::xfa"
"Text::Unidecode::xfb" "Text::Unidecode::xfc" "Text::Unidecode::xfd"
"Text::Unidecode::xfe" "Text::Unidecode::xff" "Text::Wrap" "Text::WrapI18N"
"Thread" "Thread::Queue" "Thread::Semaphore" "Tie::Array" "Tie::File"
"Tie::Handle" "Tie::Hash" "Tie::Hash::NamedCapture" "Tie::IxHash"
"Tie::Memoize" "Tie::RefHash" "Tie::Scalar" "Tie::StdHandle"
"Tie::SubstrHash" "Time::HiRes" "Time::Local" "Time::Piece" "Time::Seconds"
"Time::Zone" "Time::gmtime" "Time::localtime" "Time::tm" "Try::Tiny"
"UNIVERSAL" "URI" "URI::Escape" "URI::Heuristic" "URI::IRI"
"URI::QueryParam" "URI::Split" "URI::URL" "URI::WithBase" "URI::_foreign"
"URI::_generic" "URI::_idna" "URI::_ldap" "URI::_login" "URI::_punycode"
"URI::_query" "URI::_segment" "URI::_server" "URI::_userpass" "URI::data"
"URI::file" "URI::file::Base" "URI::file::FAT" "URI::file::Mac"
"URI::file::OS2" "URI::file::QNX" "URI::file::Unix" "URI::file::Win32"
"URI::ftp" "URI::gopher" "URI::http" "URI::https" "URI::ldap" "URI::ldapi"
"URI::ldaps" "URI::mailto" "URI::mms" "URI::news" "URI::nntp" "URI::pop"
"URI::rlogin" "URI::rsync" "URI::rtsp" "URI::rtspu" "URI::sip" "URI::sips"
"URI::snews" "URI::ssh" "URI::telnet" "URI::tn3270" "URI::urn"
"URI::urn::isbn" "URI::urn::oid" "UUID" "Unicode::Collate"
"Unicode::Collate::CJK::Big5" "Unicode::Collate::CJK::GB2312"
"Unicode::Collate::CJK::JISX0208" "Unicode::Collate::CJK::Korean"
"Unicode::Collate::CJK::Pinyin" "Unicode::Collate::CJK::Stroke"
"Unicode::Collate::CJK::Zhuyin" "Unicode::Collate::Locale"
"Unicode::Normalize" "Unicode::UCD" "User::grent" "User::pwent"
"WWW::RobotRules" "WWW::RobotRules::AnyDBM_File" "XML::LibXML"
"XML::LibXML::Attr" "XML::LibXML::AttributeHash" "XML::LibXML::Boolean"
"XML::LibXML::CDATASection" "XML::LibXML::Comment" "XML::LibXML::Common"
"XML::LibXML::DOM" "XML::LibXML::Devel" "XML::LibXML::Document"
"XML::LibXML::DocumentFragment" "XML::LibXML::Dtd" "XML::LibXML::Element"
"XML::LibXML::ErrNo" "XML::LibXML::Error" "XML::LibXML::InputCallback"
"XML::LibXML::Literal" "XML::LibXML::Namespace" "XML::LibXML::Node"
"XML::LibXML::NodeList" "XML::LibXML::Number" "XML::LibXML::PI"
"XML::LibXML::Parser" "XML::LibXML::Pattern" "XML::LibXML::Reader"
"XML::LibXML::RegExp" "XML::LibXML::RelaxNG" "XML::LibXML::SAX"
"XML::LibXML::SAX::Builder" "XML::LibXML::SAX::Generator"
"XML::LibXML::SAX::Parser" "XML::LibXML::Schema" "XML::LibXML::Text"
"XML::LibXML::XPathContext" "XML::LibXML::XPathExpression"
"XML::NamespaceSupport" "XML::Parser" "XML::Parser::Expat"
"XML::Parser::Style::Debug" "XML::Parser::Style::Objects"
"XML::Parser::Style::Stream" "XML::Parser::Style::Subs"
"XML::Parser::Style::Tree" "XML::SAX" "XML::SAX::Base" "XML::SAX::Debian"
"XML::SAX::DocumentLocator" "XML::SAX::Exception" "XML::SAX::Expat"
"XML::SAX::Intro" "XML::SAX::ParserFactory" "XML::SAX::PurePerl"
"XML::SAX::PurePerl::DTDDecls" "XML::SAX::PurePerl::DebugHandler"
"XML::SAX::PurePerl::DocType" "XML::SAX::PurePerl::EncodingDetect"
"XML::SAX::PurePerl::Exception" "XML::SAX::PurePerl::NoUnicodeExt"
"XML::SAX::PurePerl::Productions" "XML::SAX::PurePerl::Reader"
"XML::SAX::PurePerl::Reader::NoUnicodeExt"
"XML::SAX::PurePerl::Reader::Stream" "XML::SAX::PurePerl::Reader::String"
"XML::SAX::PurePerl::Reader::URI" "XML::SAX::PurePerl::Reader::UnicodeExt"
"XML::SAX::PurePerl::UnicodeExt" "XML::SAX::PurePerl::XMLDecl" "XSLoader"
"YAML::Tiny" "_charnames" "a2p" "arybase" "attributes" "autodie"
"autodie::exception" "autodie::exception::system" "autodie::hints"
"autodie::skip" "autouse" "base" "bigint" "bignum" "bigrat" "blib" "bytes"
"charnames" "common::sense" "constant" "deprecate" "diagnostics" "encoding"
"encoding::warnings" "feature" "fields" "filetest" "if" "inc::latest"
"inc::latest::private" "integer" "less" "lib" "locale" "lwpcook" "lwptut"
"mro" "open.pod" "ops" "overload" "overload::numbers" "overloading"
"parent" "perl" "perl5004delta" "perl5005delta" "perl5100delta"
"perl5101delta" "perl5120delta" "perl5121delta" "perl5122delta"
"perl5123delta" "perl5124delta" "perl5125delta" "perl5140delta"
"perl5141delta" "perl5142delta" "perl5143delta" "perl5144delta"
"perl5160delta" "perl5161delta" "perl5162delta" "perl5163delta"
"perl5180delta" "perl5181delta" "perl5182delta" "perl561delta"
"perl56delta" "perl581delta" "perl582delta" "perl583delta" "perl584delta"
"perl585delta" "perl586delta" "perl587delta" "perl588delta" "perl589delta"
"perl58delta" "perlaix" "perlamiga" "perlapi" "perlapio" "perlartistic"
"perlbook" "perlboot" "perlbot" "perlbs2000" "perlcall" "perlce"
"perlcheat" "perlclib" "perlcn" "perlcommunity" "perlcygwin" "perldata"
"perldbmfilter" "perldebguts" "perldebtut" "perldebug" "perldelta"
"perldgux" "perldiag" "perldoc" "perldos" "perldsc" "perldtrace"
"perlebcdic" "perlembed" "perlexperiment" "perlfaq" "perlfaq1" "perlfaq2"
"perlfaq3" "perlfaq4" "perlfaq5" "perlfaq6" "perlfaq7" "perlfaq8"
"perlfaq9" "perlfilter" "perlfork" "perlform" "perlfreebsd" "perlfunc"
"perlgit" "perlglossary" "perlgpl" "perlguts" "perlhack" "perlhacktips"
"perlhacktut" "perlhaiku" "perlhist" "perlhpux" "perlhurd" "perlintern"
"perlinterp" "perlintro" "perliol" "perlipc" "perlirix" "perljp" "perlko"
"perllexwarn" "perllinux" "perllocal" "perllocale" "perllol" "perlmacos"
"perlmacosx" "perlmod" "perlmodinstall" "perlmodlib" "perlmodstyle"
"perlmroapi" "perlnetware" "perlnewmod" "perlnumber" "perlobj" "perlootut"
"perlop" "perlopenbsd" "perlopentut" "perlos2" "perlos390" "perlos400"
"perlpacktut" "perlperf" "perlplan9" "perlpod" "perlpodspec" "perlpodstyle"
"perlpolicy" "perlport" "perlpragma" "perlqnx" "perlre" "perlreapi"
"perlrebackslash" "perlrecharclass" "perlref" "perlreftut" "perlreguts"
"perlrepository" "perlrequick" "perlreref" "perlretut" "perlriscos"
"perlrun" "perlsec" "perlsolaris" "perlsource" "perlstyle" "perlsub"
"perlsymbian" "perlsyn" "perlthrtut" "perltie" "perltoc" "perltodo"
"perltooc" "perltoot" "perltrap" "perltru64" "perltw" "perlunicode"
"perlunifaq" "perluniintro" "perluniprops" "perlunitut" "perlutil"
"perlvar" "perlvms" "perlvos" "perlwin32" "perlxs" "perlxstut"
"perlxstypemap" "re" "sigtrap" "sort.pod" "strict" "subs" "threads"
"threads::shared" "unicore::Name" "utf8" "vars" "version"
"version::Internals" "vmsish" "warnings" "warnings::register"))
